server {
    listen 80;
    server_name dreammakerhub.website www.dreammakerhub.website ide.dreammakerhub.website coder.dreammakerhub.website *.coder.dreammakerhub.website ai.dreammakerhub.website play.dreammakerhub.website playground.dreammakerhub.website wonderplay-3d.dreammakerhub.website civo-test.dreammakerhub.website;
    client_max_body_size 50m;

    # For HTTP-01 fallback (if needed)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        if ($http_x_forwarded_proto != "https") {
            return 301 https://$host$request_uri;
        }
    }
}

server {
    listen 443 ssl http2;
    server_name dreammakerhub.website www.dreammakerhub.website play.dreammakerhub.website playground.dreammakerhub.website wonderplay-3d.dreammakerhub.website civo-test.dreammakerhub.website ai.dreammakerhub.website;
    client_max_body_size 50m;

    ssl_certificate /etc/letsencrypt/live/dreammakerhub.website/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dreammakerhub.website/privkey.pem;

    location / {
        proxy_pass http://web:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 443 ssl http2;
    server_name coder.dreammakerhub.website ide.dreammakerhub.website *.coder.dreammakerhub.website;
    client_max_body_size 50m;

    ssl_certificate /etc/letsencrypt/live/coder.dreammakerhub.website/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coder.dreammakerhub.website/privkey.pem;

    location / {
        proxy_pass http://coder:7080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}