import { getEventBus } from './EventBus';
import { EventNames, type EventPayload, type CodeGeneratedPayload } from './types';
import { useBuilderStore } from '../store';
import { logger } from '@/lib/logger';

export class CodeGenerationService {
  private bus = getEventBus();
  private unsubs: Array<() => void> = [];
  private generationCount = 0;

  start(): void {
    // Generate code when files are created or updated
    this.unsubs.push(
      this.bus.on(EventNames.FILE_CREATED, (event) => {
        const { path, content } = event.payload as EventPayload<typeof EventNames.FILE_CREATED>;
        logger.info(`[CodeGen] File created: ${path} (${content.length} bytes)`);
      })
    );

    this.unsubs.push(
      this.bus.on(EventNames.FILE_UPDATED, (event) => {
        const { path, content, previousContent } = event.payload as EventPayload<typeof EventNames.FILE_UPDATED>;
        const diff = content.length - previousContent.length;
        logger.info(`[CodeGen] File updated: ${path} (${diff >= 0 ? '+' : ''}${diff} bytes)`);
      })
    );

    // Listen for full state changes to generate complete output
    this.unsubs.push(
      this.bus.on(EventNames.PROJECT_STATE_CHANGED, (event) => {
        this.generationCount++;
        const { elements } = event.payload as EventPayload<typeof EventNames.PROJECT_STATE_CHANGED>;
        this.bus.emit(EventNames.CODE_GENERATION_STARTED, {
          elementIds: elements.map((e) => e.id),
        }, { batch: true });
      })
    );

    // When validation passes, emit preview update
    this.unsubs.push(
      this.bus.on(EventNames.VALIDATION_COMPLETED, (event) => {
        const validation = event.payload as EventPayload<typeof EventNames.VALIDATION_COMPLETED>;
        if (validation.passed) {
          this.emitPreviewUpdate();
        }
      })
    );
  }

  private emitPreviewUpdate(): void {
    const elements = useBuilderStore.getState().elements;
    const html = this.generateFullHtml(elements);
    const css = this.generateFullCss(elements);
    this.bus.emit(EventNames.PREVIEW_UPDATED, {
      html,
      css,
      js: '// Auto-generated by AI Wonderland Builder\nconsole.log("Builder project loaded");',
      files: [
        { path: 'index.html', content: html },
        { path: 'styles.css', content: css },
      ],
    });
  }

  private generateFullHtml(elements: any[]): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AI Wonderland Project</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <div id="app">
${elements.map((el) => this.renderElement(el, 1)).join('\n')}
  </div>
  <script>
    window.__BUILDER_STATE__ = ${JSON.stringify({ elements, version: 1 }, null, 2)};
  </script>
</body>
</html>`;
  }

  private renderElement(el: any, depth: number): string {
    const indent = '  '.repeat(depth);
    const tag = this.elementTag(el);
    const attrs = this.elementAttrs(el);
    const children = el.children?.map((c: any) => this.renderElement(c, depth + 1)).join('\n') || '';
    const content = el.props?.content || el.props?.label || '';
    const innerContent = el.props?.html || '';

    if (innerContent) {
      return `${indent}<${tag}${attrs}>\n${indent}  ${innerContent}\n${indent}</${tag}>`;
    }
    if (children) {
      return `${indent}<${tag}${attrs}>\n${children}\n${indent}</${tag}>`;
    }
    if (content || ['a', 'button', 'span', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'li', 'label', 'figcaption'].includes(tag)) {
      return `${indent}<${tag}${attrs}>${content || tag}</${tag}>`;
    }
    return `${indent}<${tag}${attrs} />`;
  }

  private elementTag(el: any): string {
    const map: Record<string, string> = {
      heading: `h${el.props?.level?.replace('h', '') || '2'}`,
      paragraph: 'p', 'rich-text': 'div', list: el.props?.listType === 'ordered' ? 'ol' : 'ul',
      quote: 'blockquote', code: 'pre', 'custom-html': 'div', 'custom-css': 'style',
      'custom-js': 'script', image: 'img', video: 'div', cover: 'div',
      'media-text': 'div', audio: 'audio', file: 'a', lottie: 'div', svg: 'div',
      'image-hotspot': 'div', avatar: 'img', 'ai-image': 'div', 'ai-tts': 'div',
      button: 'a', buttons: 'div', input: 'input', textarea: 'textarea',
      select: 'select', checkbox: 'label', radio: 'fieldset', toggle: 'label',
      rating: 'div', 'file-upload': 'div', 'contact-form': 'form',
      newsletter: 'form', search: 'div', 'wp-search': 'form', 'form-webhook': 'form',
      'ai-form': 'div', 'icon-list': 'ul', badge: 'span', 'animated-text': 'span',
      'count-up': 'span', progress: 'div', chart: 'div', 'ai-seo': 'div',
      'ai-recommend': 'div', 'wp-post': 'div', 'wp-page': 'div', 'wp-comments': 'div',
      'wp-login': 'form', 'wp-profile': 'div', 'wp-sidebar': 'aside',
      'wp-widget': 'div', 'author-box': 'div', comment: 'div', steps: 'div',
      faq: 'div', accordion: 'div', tabs: 'div', table: 'table', spacer: 'div',
      divider: 'hr', card: 'div', modal: 'div', map: 'div', embed: 'div',
      codepen: 'div', tweet: 'div', instagram: 'div', tiktok: 'div', gist: 'div',
      'wp-menu': 'nav', 'wp-breadcrumbs': 'nav', pagination: 'nav', tags: 'div',
      'back-to-top': 'a', 'social-share': 'div', hashtag: 'span',
      'product-card': 'div', 'product-grid': 'div', 'add-to-cart': 'button',
      price: 'span', quantity: 'div', 'cart-icon': 'div', checkout: 'a',
      reviews: 'div', categories: 'div', shipping: 'div',
      hero: 'section', testimonial: 'div', pricing: 'div', 'team-grid': 'div',
      'logo-cloud': 'div', cta: 'section', 'typewriter': 'span', verse: 'p',
      shortcode: 'code', php: 'code',
      section: 'section', container: 'div', columns: 'div', row: 'div',
      group: 'div', grid: 'div', flex: 'div',
    };
    return map[el.type] || 'div';
  }

  private elementAttrs(el: any): string {
    const parts: string[] = [];
    parts.push(`id="${el.id}"`);
    parts.push(`class="builder-el type-${el.type}"`);
    if (el.props?.alt && el.type !== 'avatar') parts.push(`alt="${el.props.alt}"`);
    if (el.props?.src) parts.push(`src="${el.props.src}"`);
    if (el.props?.href || el.props?.url) parts.push(`href="${el.props.href || el.props.url}"`);
    if (el.props?.placeholder) parts.push(`placeholder="${el.props.placeholder}"`);
    if (el.props?.required) parts.push('required');
    if (el.props?.disabled) parts.push('disabled');
    if (el.props?.readonly) parts.push('readonly');
    if (el.props?.['aria-label']) parts.push(`aria-label="${el.props['aria-label']}"`);
    const style = this.inlineStyle(el.styles);
    if (style) parts.push(`style="${style}"`);
    return parts.length ? ' ' + parts.join(' ') : '';
  }

  private inlineStyle(s: Record<string, any>): string {
    if (!s) return '';
    return Object.entries(s)
      .filter(([_, v]) => v != null && v !== '')
      .map(([k, v]) => `${k.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${v}`)
      .join('; ');
  }

  private generateFullCss(elements: any[]): string {
    const lines: string[] = [];
    lines.push('/* AI Wonderland Builder — Auto-generated */');
    lines.push('*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }');
    lines.push('body { font-family: Inter, system-ui, sans-serif; line-height: 1.6; -webkit-font-smoothing: antialiased; }');
    lines.push('#app { max-width: 1200px; margin: 0 auto; padding: 2rem 1rem; }');
    const seen = new Set<string>();
    for (const el of elements) {
      this.collectStyles(el, lines, seen);
    }
    lines.push('');
    lines.push('/* Responsive */');
    lines.push('@media (max-width: 768px) { #app { padding: 1rem; } }');
    return lines.join('\n');
  }

  private collectStyles(el: any, lines: string[], seen: Set<string>): void {
    const s = el.styles;
    if (s && Object.keys(s).length > 0) {
      const key = `.type-${el.type}`;
      if (!seen.has(key)) {
        seen.add(key);
        const rules = Object.entries(s)
          .filter(([_, v]) => v != null && v !== '')
          .map(([k, v]) => `  ${k.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${v};`);
        if (rules.length > 0) {
          lines.push('');
          lines.push(`${key} {`);
          lines.push(...rules);
          lines.push('}');
        }
      }
    }
    if (el.children) {
      for (const child of el.children) {
        this.collectStyles(child, lines, seen);
      }
    }
  }

  getGenerationCount(): number {
    return this.generationCount;
  }

  stop(): void {
    for (const unsub of this.unsubs) unsub();
    this.unsubs = [];
  }
}

export const codeGenerationService = new CodeGenerationService();
