coder:
  env:
    - name: CODER_ACCESS_URL
      value: "http://147.224.185.75"
    - name: CODER_WILDCARD_ACCESS_URL
      value: "*.coder.dreammakerhub.website"
    - name: CODER_DERP_FORCE_WEBSOCKETS
      value: "true"

service:
  type: LoadBalancer
  annotations:
    oci.oraclecloud.com/load-balancer-internal: "false"

ingress:
  enable: false

provisioner:
  fsGroup: 1000

postgres:
  enable: true