import {
  Confession,
  ConfessionType,
  ImpactLevel,
  LocalizedConfession,
} from "./types";

export interface ConfessionFactoryOptions {
  title: string;
  detail: string;
  truth: string;
  what: string;
  why: string;
  how: string;
  relatedStepCode?: string | null;
  machineTags?: string[];
  impactLevel?: ImpactLevel;
}

export interface LocalizedConfessionFactoryOptions
  extends ConfessionFactoryOptions {
  language: string;
}

export function createConfession(
  type: ConfessionType,
  options: ConfessionFactoryOptions
): Confession {
  const {
    title,
    detail,
    truth,
    what,
    why,
    how,
    relatedStepCode = null,
    machineTags = [],
    impactLevel,
  } = options;

  return {
    type,
    title,
    detail,
    truth: truth || detail,
    what: what || "",
    why: why || "",
    how: how || "",
    relatedStepCode,
    machineTags,
    impactLevel: impactLevel ?? getDefaultImpactLevel(type),
  };
}

export function createLocalizedConfession(
  type: ConfessionType,
  options: LocalizedConfessionFactoryOptions
): LocalizedConfession {
  return {
    ...createConfession(type, options),
    language: options.language,
  };
}

function getDefaultImpactLevel(type: ConfessionType): ImpactLevel {
  switch (type) {
    case "RISK_FLAG":
    case "REJECTED_ACTION":
    case "HALLUCINATION_DETECTED":
      return "HIGH";
    case "CORRECTION":
    case "TRUTH_VERIFIED":
      return "MEDIUM";
    default:
      return "LOW";
  }
}

export const createUncertaintyConfession = (
  opts: LocalizedConfessionFactoryOptions
) => createLocalizedConfession("UNCERTAINTY", opts);

export const createRejectedActionConfession = (
  opts: LocalizedConfessionFactoryOptions
) => createLocalizedConfession("REJECTED_ACTION", opts);

export const createRiskFlagConfession = (
  opts: LocalizedConfessionFactoryOptions
) => createLocalizedConfession("RISK_FLAG", opts);

export const createLimitationConfession = (
  opts: LocalizedConfessionFactoryOptions
) => createLocalizedConfession("LIMITATION", opts);

export const createCorrectionConfession = (
  opts: LocalizedConfessionFactoryOptions
) => createLocalizedConfession("CORRECTION", opts);

export const createHallucinationConfession = (
  opts: LocalizedConfessionFactoryOptions
) => createLocalizedConfession("HALLUCINATION_DETECTED", opts);

export const createTruthVerifiedConfession = (
  opts: LocalizedConfessionFactoryOptions
) => createLocalizedConfession("TRUTH_VERIFIED", opts);


// ========================================================
// Pipeline Router: Streams data directly to your cluster backend
// ========================================================

/**
 * Dispatches a factory-generated confession payload to your workflow pipeline webhook
 * @param agentName Name of the executing agent ("Alice", "Simple Rick", "Spirit Guide")
 * @param confession Structured data generated by your factory methods
 */
export async function streamConfessionToPipeline(agentName: string, confession: Confession | LocalizedConfession) {
  // Point this to your backend execution URL (e.g. Railway webhook or n8n webhook node trigger)
  const pipelineWebhookUrl = process.env.NEXT_PUBLIC_PIPELINE_WEBHOOK_URL || 'YOUR_BACKEND_PIPELINE_ENDPOINT';

  try {
    const response = await fetch(pipelineWebhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        source: "execution_pipeline",
        agentName,
        timestamp: new Date().toISOString(),
        payload: confession
      })
    });

    if (!response.ok) {
      throw new Error(`Pipeline responded with status: ${response.status}`);
    }

    return true;
  } catch (error) {
    console.error("[Pipeline Error] Failed to stream agent confirmation data:", error);
    return false;
  }
}
