apiVersion: v1
kind: LimitRange
metadata:
  name: wonder-limits
  namespace: wonderspace
spec:
  limits:
  - max:
      memory: "4Gi"
      cpu: "4000m"
    min:
      memory: "128Mi"
      cpu: "50m"
    default:
      memory: "1Gi"
      cpu: "1000m"
    defaultRequest:
      memory: "512Mi"
      cpu: "250m"
    type: Container