apiVersion: v1
kind: ConfigMap
metadata:
  name: wonderland-config
  namespace: wonderland
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_URL: "https://dreammakerhub.website"
  NEXT_PUBLIC_WORKSPACE_DOMAIN: "dreammakerhub.website"
  WORKSPACE_DOMAIN: "dreammakerhub.website"
  CODER_ACCESS_URL: "https://dreammakerhub.website"
  CODER_WILDCARD_ACCESS_URL: "*.ide.dreammakerhub.website"