apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wonderland-ide-ingress
  namespace: wonderland
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  tls:
    - hosts:
        - "*.ide.dreammakerhub.website"
      secretName: dreammakerhub-ide-tls
  rules:
    - host: "*.ide.dreammakerhub.website"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wonderland-ide
                port:
                  number: 80