apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ide-ingress
  namespace: coder
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  ingressClassName: nginx
  rules:
  - host: ide.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coder-ide
            port:
              number: 80
  - host: playcanvas.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: playcanvas-webgl
            port:
              number: 80