apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ide-ingress
  namespace: coder
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dreammakerhub.website
    - www.dreammakerhub.website
    secretName: wonder-web-tls
  - hosts:
    - play.dreammakerhub.website
    - wonderplay.dreammakerhub.website
    secretName: wonderplay-tls
  - hosts:
    - ai.dreammakerhub.website
    secretName: ai-playground-tls
  rules:
  - host: ide.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coder-ide
            port:
              number: 80
  - host: playcanvas.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: playcanvas-webgl
            port:
              number: 80
  - host: wonderplay.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wonderplay-service
            port:
              number: 3090
  - host: play.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wonderplay-service
            port:
              number: 3090
  - host: ai.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wonder-web
            port:
              number: 80

  - host: dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wonder-web
            port:
              number: 80
  - host: www.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wonder-web
            port:
              number: 80