apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coder-ingress
  namespace: coder
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - coder.dreammakerhub.website
    secretName: coder-tls
  rules:
  - host: coder.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coder
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ide-ingress
  namespace: coder
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ide.dreammakerhub.website
    secretName: ide-tls
  rules:
  - host: ide.dreammakerhub.website
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coder-ide
            port:
              number: 80
