import type { BlockDefinition } from '../types';

export const AUTH_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// AUTH
// ═══════════════════════════════════════
  { name: 'Login Form', type: 'login-form', icon: '🔐', category: 'auth', description: 'User login form', defaultProps: { title: 'Sign In', usernameLabel: 'Email', passwordLabel: 'Password', submitText: 'Sign In', showRemember: true, showRegister: true, showForgot: true, redirectUrl: '/dashboard' }, defaultStyles: { maxWidth: '400px', margin: '0 auto', padding: '2rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'submitText', label: 'Submit Text', type: 'text' }, { key: 'showRemember', label: 'Show Remember', type: 'toggle' }, { key: 'showRegister', label: 'Show Register Link', type: 'toggle' }, { key: 'showForgot', label: 'Show Forgot Password', type: 'toggle' }, { key: 'redirectUrl', label: 'Redirect URL', type: 'text' }] },
  { name: 'Register Form', type: 'register-form', icon: '📝', category: 'auth', description: 'User registration form', defaultProps: { title: 'Create Account', submitText: 'Sign Up', showName: true, showPasswordConfirm: true, termsText: 'I agree to the Terms & Conditions', redirectUrl: '/dashboard' }, defaultStyles: { maxWidth: '500px', margin: '0 auto', padding: '2rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'submitText', label: 'Submit Text', type: 'text' }, { key: 'showName', label: 'Show Name Field', type: 'toggle' }, { key: 'showPasswordConfirm', label: 'Show Confirm Password', type: 'toggle' }, { key: 'termsText', label: 'Terms Text', type: 'text' }, { key: 'redirectUrl', label: 'Redirect URL', type: 'text' }] },
  { name: 'Password Reset', type: 'password-reset', icon: '🔑', category: 'auth', description: 'Password reset form', defaultProps: { title: 'Reset Password', emailLabel: 'Email', submitText: 'Send Reset Link', successMessage: 'Check your email for a reset link.', mode: 'request' }, defaultStyles: { maxWidth: '400px', margin: '0 auto', padding: '2rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'submitText', label: 'Submit Text', type: 'text' }, { key: 'successMessage', label: 'Success Message', type: 'text' }, { key: 'mode', label: 'Mode', type: 'select', options: [{ label: 'Request', value: 'request' }, { label: 'Reset', value: 'reset' }] }] },
  { name: 'OAuth Buttons', type: 'oauth-buttons', icon: '🔗', category: 'auth', description: 'Social login OAuth buttons', defaultProps: { providers: ['google', 'github', 'facebook'], layout: 'row', size: 'md', showDivider: true, dividerText: 'or continue with' }, defaultStyles: { display: 'flex', flexDirection: 'column', gap: '0.75rem', padding: '1rem 0' }, editableProps: [{ key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Row', value: 'row' }, { label: 'Column', value: 'column' }] }, { key: 'size', label: 'Size', type: 'select', options: [{ label: 'Small', value: 'sm' }, { label: 'Medium', value: 'md' }, { label: 'Large', value: 'lg' }] }, { key: 'showDivider', label: 'Show Divider', type: 'toggle' }, { key: 'dividerText', label: 'Divider Text', type: 'text' }] },
];
