import type { BlockDefinition } from '../types';

export const BLOG_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// BLOG
// ═══════════════════════════════════════
  { name: 'WP Post', type: 'wp-post', icon: '📝', category: 'blog', description: 'Latest WP posts loop', defaultProps: { title: 'Latest Posts', count: 3, postType: 'post', showExcerpt: true }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'count', label: 'Count', type: 'number' }, { key: 'showExcerpt', label: 'Show Excerpt', type: 'toggle' }] },
  { name: 'WP Page', type: 'wp-page', icon: '📄', category: 'blog', description: 'WP page embed', defaultProps: { title: 'About', wpSlug: 'about' }, defaultStyles: { padding: '2rem', maxWidth: '1200px', margin: '0 auto' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'wpSlug', label: 'WP Slug', type: 'text' }] },
  { name: 'WP Comments', type: 'wp-comments', icon: '💭', category: 'blog', description: 'WP comments section', defaultProps: { title: 'Comments', showForm: true }, defaultStyles: { padding: '1rem', borderTop: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'showForm', label: 'Show Form', type: 'toggle' }] },
  { name: 'WP Login', type: 'wp-login', icon: '🔐', category: 'blog', description: 'WP login / logout form', defaultProps: { redirectUrl: '', showRegister: true }, defaultStyles: { maxWidth: '400px', margin: '0 auto', padding: '2rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem' }, editableProps: [{ key: 'redirectUrl', label: 'Redirect URL', type: 'text' }, { key: 'showRegister', label: 'Show Register', type: 'toggle' }] },
  { name: 'WP User Profile', type: 'wp-profile', icon: '👤', category: 'blog', description: 'WP user profile card', defaultProps: { showAvatar: true, showBio: true }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'showAvatar', label: 'Show Avatar', type: 'toggle' }, { key: 'showBio', label: 'Show Bio', type: 'toggle' }] },
  { name: 'WP Sidebar', type: 'wp-sidebar', icon: '📑', category: 'blog', description: 'Dynamic WP sidebar widget area', defaultProps: { title: 'Sidebar' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }] },
  { name: 'WP Widget', type: 'wp-widget', icon: '🧩', category: 'blog', description: 'WP widget area', defaultProps: { widgetArea: 'sidebar-1', title: 'Widget' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'widgetArea', label: 'Widget Area ID', type: 'text' }] },
  { name: 'Author Box', type: 'author-box', icon: '👤', category: 'blog', description: 'Author bio card', defaultProps: { name: 'John Doe', bio: 'Writer and creator.', avatar: '', role: 'Author' }, defaultStyles: { display: 'flex', gap: '1rem', padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', alignItems: 'flex-start' }, editableProps: [{ key: 'name', label: 'Name', type: 'text' }, { key: 'bio', label: 'Bio', type: 'textarea' }, { key: 'role', label: 'Role', type: 'text' }, { key: 'avatar', label: 'Avatar URL', type: 'image' }] },
  { name: 'Comment', type: 'comment', icon: '💬', category: 'blog', description: 'Single comment display', defaultProps: { author: 'Alice', avatar: '', content: 'Great post! Thanks for sharing.', date: '2 hours ago' }, defaultStyles: { display: 'flex', gap: '0.75rem', padding: '1rem 0', borderBottom: '1px solid rgba(255,255,255,0.08)' }, editableProps: [{ key: 'author', label: 'Author', type: 'text' }, { key: 'content', label: 'Comment', type: 'textarea' }, { key: 'date', label: 'Date', type: 'text' }] },
  { name: 'Steps', type: 'steps', icon: '👣', category: 'blog', description: 'Step-by-step process or timeline', defaultProps: { steps: [{ title: 'Describe', desc: 'Tell AI what you want.' }, { title: 'Build', desc: 'AI generates the site.' }, { title: 'Publish', desc: 'Export to WordPress.' }], layout: 'steps' }, defaultStyles: { display: 'flex', gap: '2rem', padding: '2rem 0' }, editableProps: [{ key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Steps', value: 'steps' }, { label: 'Timeline', value: 'timeline' }] }] },
  { name: 'FAQ', type: 'faq', icon: '❓', category: 'blog', description: 'Accordion FAQ section', defaultProps: { items: [{ q: 'How does it work?', a: 'Describe your site and AI builds it.' }, { q: 'Is it WordPress compatible?', a: 'Yes, exports to WP.' }] }, defaultStyles: { padding: '1rem 0' }, editableProps: [] },
  { name: 'Blog Archive', type: 'blog-archive', icon: '📚', category: 'blog', description: 'Full blog archive with pagination', defaultProps: { title: 'Blog', postsPerPage: 10, showSearch: true, layout: 'grid' }, defaultStyles: { padding: '1rem 0', maxWidth: '1200px', margin: '0 auto' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'postsPerPage', label: 'Posts Per Page', type: 'number' }, { key: 'showSearch', label: 'Show Search', type: 'toggle' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Grid', value: 'grid' }, { label: 'List', value: 'list' }, { label: 'Masonry', value: 'masonry' }] }] },
  { name: 'Recent Posts', type: 'recent-posts', icon: '🕐', category: 'blog', description: 'Recent posts sidebar list', defaultProps: { title: 'Recent Posts', count: 5, showDate: true, showThumbnail: false }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'count', label: 'Count', type: 'number' }, { key: 'showDate', label: 'Show Date', type: 'toggle' }, { key: 'showThumbnail', label: 'Show Thumbnail', type: 'toggle' }] },
  { name: 'Category List', type: 'category-list', icon: '📂', category: 'blog', description: 'Blog categories list with post counts', defaultProps: { title: 'Categories', showCount: true, layout: 'list' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'showCount', label: 'Show Post Count', type: 'toggle' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'List', value: 'list' }, { label: 'Cloud', value: 'cloud' }] }] },
  { name: 'Search Results', type: 'search-results', icon: '🔍', category: 'blog', description: 'Blog search results display', defaultProps: { title: 'Search Results', placeholder: 'Search the blog...', emptyMessage: 'No results found.', layout: 'list' }, defaultStyles: { padding: '1rem 0' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'emptyMessage', label: 'Empty Message', type: 'text' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'List', value: 'list' }, { label: 'Grid', value: 'grid' }] }] },
];
