import type { BlockDefinition } from '../types';

export const BLOG_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// BLOG
// ═══════════════════════════════════════
  { name: 'WP Post', type: 'wp-post', icon: '📝', category: 'blog', description: 'Latest WP posts loop', defaultProps: { title: 'Latest Posts', count: 3, postType: 'post', showExcerpt: true }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'count', label: 'Count', type: 'number' }, { key: 'showExcerpt', label: 'Show Excerpt', type: 'toggle' }] },
  { name: 'WP Page', type: 'wp-page', icon: '📄', category: 'blog', description: 'WP page embed', defaultProps: { title: 'About', wpSlug: 'about' }, defaultStyles: { padding: '2rem', maxWidth: '1200px', margin: '0 auto' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'wpSlug', label: 'WP Slug', type: 'text' }] },
  { name: 'WP Comments', type: 'wp-comments', icon: '💭', category: 'blog', description: 'WP comments section', defaultProps: { title: 'Comments', showForm: true }, defaultStyles: { padding: '1rem', borderTop: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'showForm', label: 'Show Form', type: 'toggle' }] },
  { name: 'WP Login', type: 'wp-login', icon: '🔐', category: 'blog', description: 'WP login / logout form', defaultProps: { redirectUrl: '', showRegister: true }, defaultStyles: { maxWidth: '400px', margin: '0 auto', padding: '2rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem' }, editableProps: [{ key: 'redirectUrl', label: 'Redirect URL', type: 'text' }, { key: 'showRegister', label: 'Show Register', type: 'toggle' }] },
  { name: 'WP User Profile', type: 'wp-profile', icon: '👤', category: 'blog', description: 'WP user profile card', defaultProps: { showAvatar: true, showBio: true }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'showAvatar', label: 'Show Avatar', type: 'toggle' }, { key: 'showBio', label: 'Show Bio', type: 'toggle' }] },
  { name: 'WP Sidebar', type: 'wp-sidebar', icon: '📑', category: 'blog', description: 'Dynamic WP sidebar widget area', defaultProps: { title: 'Sidebar' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }] },
  { name: 'WP Widget', type: 'wp-widget', icon: '🧩', category: 'blog', description: 'WP widget area', defaultProps: { widgetArea: 'sidebar-1', title: 'Widget' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'widgetArea', label: 'Widget Area ID', type: 'text' }] },
  { name: 'Author Box', type: 'author-box', icon: '👤', category: 'blog', description: 'Author bio card', defaultProps: { name: 'John Doe', bio: 'Writer and creator.', avatar: '', role: 'Author' }, defaultStyles: { display: 'flex', gap: '1rem', padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', alignItems: 'flex-start' }, editableProps: [{ key: 'name', label: 'Name', type: 'text' }, { key: 'bio', label: 'Bio', type: 'textarea' }, { key: 'role', label: 'Role', type: 'text' }, { key: 'avatar', label: 'Avatar URL', type: 'image' }] },
  { name: 'Comment', type: 'comment', icon: '💬', category: 'blog', description: 'Single comment display', defaultProps: { author: 'Alice', avatar: '', content: 'Great post! Thanks for sharing.', date: '2 hours ago' }, defaultStyles: { display: 'flex', gap: '0.75rem', padding: '1rem 0', borderBottom: '1px solid rgba(255,255,255,0.08)' }, editableProps: [{ key: 'author', label: 'Author', type: 'text' }, { key: 'content', label: 'Comment', type: 'textarea' }, { key: 'date', label: 'Date', type: 'text' }] },
  { name: 'Steps', type: 'steps', icon: '👣', category: 'blog', description: 'Step-by-step process or timeline', defaultProps: { steps: [{ title: 'Describe', desc: 'Tell AI what you want.' }, { title: 'Build', desc: 'AI generates the site.' }, { title: 'Publish', desc: 'Export to WordPress.' }], layout: 'steps' }, defaultStyles: { display: 'flex', gap: '2rem', padding: '2rem 0' }, editableProps: [{ key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Steps', value: 'steps' }, { label: 'Timeline', value: 'timeline' }] }] },
  { name: 'FAQ', type: 'faq', icon: '❓', category: 'blog', description: 'Accordion FAQ section', defaultProps: { items: [{ q: 'How does it work?', a: 'Describe your site and AI builds it.' }, { q: 'Is it WordPress compatible?', a: 'Yes, exports to WP.' }] }, defaultStyles: { padding: '1rem 0' }, editableProps: [] },
  { name: 'Blog Archive', type: 'blog-archive', icon: '📚', category: 'blog', description: 'Full blog archive with pagination', defaultProps: { title: 'Blog', postsPerPage: 10, showSearch: true, layout: 'grid' }, defaultStyles: { padding: '1rem 0', maxWidth: '1200px', margin: '0 auto' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'postsPerPage', label: 'Posts Per Page', type: 'number' }, { key: 'showSearch', label: 'Show Search', type: 'toggle' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Grid', value: 'grid' }, { label: 'List', value: 'list' }, { label: 'Masonry', value: 'masonry' }] }] },
  { name: 'Recent Posts', type: 'recent-posts', icon: '🕐', category: 'blog', description: 'Recent posts sidebar list', defaultProps: { title: 'Recent Posts', count: 5, showDate: true, showThumbnail: false }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'count', label: 'Count', type: 'number' }, { key: 'showDate', label: 'Show Date', type: 'toggle' }, { key: 'showThumbnail', label: 'Show Thumbnail', type: 'toggle' }] },
  { name: 'Category List', type: 'category-list', icon: '📂', category: 'blog', description: 'Blog categories list with post counts', defaultProps: { title: 'Categories', showCount: true, layout: 'list' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'showCount', label: 'Show Post Count', type: 'toggle' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'List', value: 'list' }, { label: 'Cloud', value: 'cloud' }] }] },
  { name: 'Search Results', type: 'search-results', icon: '🔍', category: 'blog', description: 'Blog search results display', defaultProps: { title: 'Search Results', placeholder: 'Search the blog...', emptyMessage: 'No results found.', layout: 'list' }, defaultStyles: { padding: '1rem 0' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'emptyMessage', label: 'Empty Message', type: 'text' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'List', value: 'list' }, { label: 'Grid', value: 'grid' }] }] },
  { name: 'Magazine Grid', type: 'magazine-grid', icon: '📰', category: 'blog', description: 'Editorial featured + stacked posts layout', defaultProps: { posts: [{ title: 'Designing in prompts', excerpt: 'How AI changes the craft.', tag: 'Design', minutes: 6 }, { title: 'Ship weekly', excerpt: 'Cadence beats perfection.', tag: 'Process', minutes: 4 }], featuredIndex: 0 }, defaultStyles: { display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '1.5rem', padding: '2rem', maxWidth: '1100px', margin: '0 auto' }, editableProps: [{ key: 'featuredIndex', label: 'Featured Post #', type: 'number' }] },
  { name: 'Post List Rows', type: 'post-list-rows', icon: '📃', category: 'blog', description: 'Compact horizontal post rows', defaultProps: { rows: [{ title: 'Row post', date: 'Aug 20', minutes: 3 }], showThumbs: true }, defaultStyles: { display: 'grid', gap: '0.75rem', padding: '1rem', maxWidth: '760px', margin: '0 auto' }, editableProps: [{ key: 'showThumbs', label: 'Show Thumbnails', type: 'toggle' }] },
  { name: 'Related Posts', type: 'related-posts', icon: '🔗', category: 'blog', description: 'You-might-like cards under an article', defaultProps: { heading: 'Keep reading', count: 3 }, defaultStyles: { padding: '1.5rem', maxWidth: '900px', margin: '0 auto' }, editableProps: [{ key: 'heading', label: 'Heading', type: 'text' }, { key: 'count', label: 'Post Count', type: 'number' }] },
  { name: 'Tag Filter Bar', type: 'tag-filter-bar', icon: '🏷️', category: 'blog', description: 'Horizontal scrollable topic chips', defaultProps: { tags: ['All', 'AI', 'Design', '3D', 'Launches'], active: 'All' }, defaultStyles: { display: 'flex', gap: '0.5rem', overflowX: 'auto', padding: '0.75rem 1rem' }, editableProps: [{ key: 'active', label: 'Active Tag', type: 'text' }] },
  { name: 'Reading Progress', type: 'reading-progress', icon: '📈', category: 'blog', description: 'Scroll progress indicator bar', defaultProps: { color: '#a855f7', thickness: 3 }, defaultStyles: { position: 'sticky', top: '0px' }, editableProps: [{ key: 'thickness', label: 'Thickness (px)', type: 'number' }] },
  { name: 'Table of Contents', type: 'table-of-contents', icon: '🧭', category: 'blog', description: 'Auto outline with anchor links', defaultProps: { heading: 'On this page', items: ['Introduction', 'Setup', 'Advanced'], depth: 2 }, defaultStyles: { fontSize: '0.85rem', padding: '1rem', borderRadius: '0.6rem', backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', maxWidth: '280px' }, editableProps: [{ key: 'heading', label: 'Heading', type: 'text' }] },
  { name: 'Featured Post Hero', type: 'featured-post-hero', icon: '🌟', category: 'blog', description: 'Big image banner for flagship article', defaultProps: { title: 'The prompt-native web', category: 'Vision', minutes: 11, image: '', href: '#' }, defaultStyles: { minHeight: '320px', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', padding: '2rem', borderRadius: '1rem', color: '#fff', backgroundImage: 'linear-gradient(180deg, transparent, rgba(0,0,0,0.75))', backgroundSize: 'cover' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'category', label: 'Category', type: 'text' }, { key: 'minutes', label: 'Read Minutes', type: 'number' }, { key: 'image', label: 'Background Image', type: 'image' }, { key: 'href', label: 'Link', type: 'text' }] },
  { name: 'Post Footer CTA', type: 'post-footer-cta', icon: '🎯', category: 'blog', description: 'End-of-article conversion block', defaultProps: { text: 'Enjoyed this? Build your own site in minutes.', cta: 'Try it free', href: '/subscription' }, defaultStyles: { textAlign: 'center', padding: '1.5rem', borderRadius: '0.75rem', background: 'linear-gradient(135deg, rgba(168,85,247,0.12), rgba(34,211,238,0.08))', border: '1px solid rgba(168,85,247,0.25)', margin: '2rem auto', maxWidth: '640px' }, editableProps: [{ key: 'text', label: 'Text', type: 'textarea' }, { key: 'cta', label: 'Button Text', type: 'text' }, { key: 'href', label: 'Button Link', type: 'text' }] },
  { name: 'Blog Sidebar', type: 'blog-sidebar', icon: '🗃️', category: 'blog', description: 'Sticky sidebar with search + recent', defaultProps: { showSearch: true, recentTitles: ['Prompt patterns', 'WebGL tips'] }, defaultStyles: { display: 'grid', gap: '1.25rem', padding: '1rem' }, editableProps: [{ key: 'showSearch', label: 'Show Search', type: 'toggle' }] },
];
