import type { BlockDefinition } from '../types';

export const COMMERCE_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// COMMERCE
// ═══════════════════════════════════════
  { name: 'Product Card', type: 'product-card', icon: '🛍️', category: 'commerce', description: 'Single product card', defaultProps: { name: 'Product Name', price: '$29.99', image: 'https://picsum.photos/400/400', currency: 'USD', rating: 4.5 }, defaultStyles: { padding: '1.25rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', textAlign: 'center' }, editableProps: [{ key: 'name', label: 'Product Name', type: 'text' }, { key: 'price', label: 'Price', type: 'text' }, { key: 'image', label: 'Image URL', type: 'image' }, { key: 'rating', label: 'Rating', type: 'range' }] },
  { name: 'Product Grid', type: 'product-grid', icon: '🏪', category: 'commerce', description: 'Product listing grid', defaultProps: { columns: 3, count: 6 }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1.5rem', padding: '1rem 0' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'range' }] },
  { name: 'Add to Cart', type: 'add-to-cart', icon: '🛒', category: 'commerce', description: 'Add to cart button', defaultProps: { productId: '123', label: 'Add to Cart', variant: 'primary', quantity: 1 }, defaultStyles: { backgroundColor: '#7c3aed', color: '#ffffff', padding: '0.75rem 1.5rem', borderRadius: '0.5rem', fontWeight: '600', border: 'none', cursor: 'pointer', fontSize: '0.875rem' }, editableProps: [{ key: 'label', label: 'Button Text', type: 'text' }, { key: 'productId', label: 'Product ID', type: 'text' }, { key: 'quantity', label: 'Default Qty', type: 'number' }] },
  { name: 'Price', type: 'price', icon: '💲', category: 'commerce', description: 'Product price display', defaultProps: { amount: '29.99', currency: 'USD', compareAt: '', sale: false }, defaultStyles: { fontSize: '1.5rem', fontWeight: '700', color: '#7c3aed', marginBottom: '0.5rem' }, editableProps: [{ key: 'amount', label: 'Price', type: 'text' }, { key: 'currency', label: 'Currency', type: 'select', options: [{ label: 'USD', value: 'USD' }, { label: 'EUR', value: 'EUR' }, { label: 'GBP', value: 'GBP' }, { label: 'INR', value: 'INR' }] }, { key: 'compareAt', label: 'Compare At', type: 'text' }, { key: 'sale', label: 'On Sale', type: 'toggle' }] },
  { name: 'Quantity Selector', type: 'quantity', icon: '➕', category: 'commerce', description: 'Quantity increment/decrement', defaultProps: { min: 1, max: 99, value: 1 }, defaultStyles: { display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }, editableProps: [{ key: 'min', label: 'Min', type: 'number' }, { key: 'max', label: 'Max', type: 'number' }, { key: 'value', label: 'Default', type: 'number' }] },
  { name: 'Cart Icon', type: 'cart-icon', icon: '🛒', category: 'commerce', description: 'Mini cart with item count', defaultProps: { count: 0, url: '/cart', iconSize: '1.25rem' }, defaultStyles: { position: 'relative', display: 'inline-flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', color: '#ffffff' }, editableProps: [{ key: 'url', label: 'Cart URL', type: 'text' }, { key: 'iconSize', label: 'Icon Size', type: 'text' }] },
  { name: 'Checkout Button', type: 'checkout', icon: '💳', category: 'commerce', description: 'Proceed to checkout button', defaultProps: { label: 'Checkout', url: '/checkout', total: '$29.99' }, defaultStyles: { backgroundColor: '#059669', color: '#ffffff', padding: '0.875rem 2rem', borderRadius: '0.5rem', fontWeight: '700', border: 'none', cursor: 'pointer', fontSize: '1rem', width: '100%', textAlign: 'center' }, editableProps: [{ key: 'label', label: 'Text', type: 'text' }, { key: 'url', label: 'URL', type: 'text' }, { key: 'total', label: 'Total', type: 'text' }] },
  { name: 'Reviews', type: 'reviews', icon: '⭐', category: 'commerce', description: 'Product reviews section', defaultProps: { average: 4.5, count: 128, showForm: true }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'average', label: 'Avg Rating', type: 'range' }, { key: 'count', label: 'Review Count', type: 'number' }, { key: 'showForm', label: 'Show Review Form', type: 'toggle' }] },
  { name: 'Categories', type: 'categories', icon: '📁', category: 'commerce', description: 'Product categories list', defaultProps: { categories: ['Electronics', 'Clothing', 'Home', 'Sports', 'Books'], layout: 'list' }, defaultStyles: { display: 'flex', flexDirection: 'column', gap: '0.5rem', padding: '0.5rem 0' }, editableProps: [{ key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'List', value: 'list' }, { label: 'Grid', value: 'grid' }, { label: 'Tags', value: 'tags' }] }] },
  { name: 'Shipping Info', type: 'shipping', icon: '🚚', category: 'commerce', description: 'Shipping details display', defaultProps: { cost: 'Free', estimate: '3-5 business days', note: 'Free shipping on orders over $50' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)', fontSize: '0.875rem', marginBottom: '0.5rem' }, editableProps: [{ key: 'cost', label: 'Cost', type: 'text' }, { key: 'estimate', label: 'Estimate', type: 'text' }, { key: 'note', label: 'Note', type: 'text' }] },
  { name: 'Wishlist Button', type: 'wishlist', icon: '❤️', category: 'commerce', description: 'Add to wishlist toggle button', defaultProps: { productId: '123', label: 'Wishlist', addedLabel: 'Wished', showIcon: true }, defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.15)', cursor: 'pointer', fontSize: '0.875rem', color: '#f43f5e', background: 'transparent' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'addedLabel', label: 'Added Label', type: 'text' }, { key: 'showIcon', label: 'Show Icon', type: 'toggle' }] },
  { name: 'Coupon Code', type: 'coupon', icon: '🏷️', category: 'commerce', description: 'Coupon code input and display', defaultProps: { placeholder: 'Enter coupon code', buttonText: 'Apply', code: '', discount: '' }, defaultStyles: { display: 'flex', gap: '0.5rem', padding: '0.75rem 0', borderTop: '1px solid rgba(255,255,255,0.1)', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: '0.5rem' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }] },
  { name: 'Size Selector', type: 'size-selector', icon: '📏', category: 'commerce', description: 'Product size picker', defaultProps: { sizes: ['XS', 'S', 'M', 'L', 'XL'], selected: 'M', variant: 'rounded' }, defaultStyles: { display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '1rem' }, editableProps: [{ key: 'variant', label: 'Style', type: 'select', options: [{ label: 'Rounded', value: 'rounded' }, { label: 'Square', value: 'square' }, { label: 'Pills', value: 'pills' }] }] },
  { name: 'Color Swatches', type: 'color-swatches', icon: '🎨', category: 'commerce', description: 'Product color option picker', defaultProps: { colors: [{ label: 'Red', value: '#ef4444' }, { label: 'Blue', value: '#3b82f6' }, { label: 'Green', value: '#22c55e' }, { label: 'Black', value: '#000000' }], selected: '#3b82f6', size: '32px' }, defaultStyles: { display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '1rem' }, editableProps: [{ key: 'size', label: 'Swatch Size', type: 'text' }] },
  { name: 'Order Summary', type: 'order-summary', icon: '📋', category: 'commerce', description: 'Order details summary table', defaultProps: { items: [{ name: 'Product 1', qty: 1, price: '$29.99' }, { name: 'Product 2', qty: 2, price: '$19.99' }], subtotal: '$69.97', shipping: 'Free', tax: '$7.00', total: '$76.97' }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', fontSize: '0.875rem' }, editableProps: [{ key: 'subtotal', label: 'Subtotal', type: 'text' }, { key: 'shipping', label: 'Shipping', type: 'text' }, { key: 'tax', label: 'Tax', type: 'text' }, { key: 'total', label: 'Total', type: 'text' }] },
  { name: 'Cart Drawer', type: 'cart-drawer', icon: '🛒', category: 'commerce', description: 'Slide-out cart summary panel', defaultProps: { title: 'Your cart', items: [{ name: 'Studio Tee', qty: 1, price: '$28.00' }], subtotalLabel: 'Subtotal', checkoutLabel: 'Checkout', emptyText: 'Your cart is empty' }, defaultStyles: { display: 'flex', flexDirection: 'column', gap: '0.75rem', padding: '1.25rem', borderRadius: '0.75rem', backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.12)', width: '340px' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'checkoutLabel', label: 'Checkout Text', type: 'text' }, { key: 'emptyText', label: 'Empty Text', type: 'text' }] },

  { name: 'Cart Icon Button', type: 'cart-icon-button', icon: '🛍️', category: 'commerce', description: 'Header cart button with count badge', defaultProps: { count: 2, iconSize: 22 }, defaultStyles: { position: 'relative', display: 'inline-flex', padding: '0.5rem', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.15)', cursor: 'pointer', background: 'transparent', color: '#fff' }, editableProps: [{ key: 'count', label: 'Item Count', type: 'number' }] },

  { name: 'Express Checkout', type: 'express-checkout', icon: '⚡', category: 'commerce', description: 'Wallet quick-pay buttons row', defaultProps: { showApplePay: true, showGooglePay: true, showPaypal: true, dividerLabel: 'or pay with card' }, defaultStyles: { display: 'grid', gap: '0.5rem', maxWidth: '380px', margin: '0 auto', padding: '1rem 0' }, editableProps: [{ key: 'dividerLabel', label: 'Divider Text', type: 'text' }] },

  { name: 'Order Tracker', type: 'order-tracker', icon: '📦', category: 'commerce', description: 'Order status timeline', defaultProps: { orderNo: '#1042', steps: ['Confirmed', 'Packed', 'Shipped', 'Delivered'], currentStep: 2, carrier: 'NovaExpress' }, defaultStyles: { padding: '1.25rem', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '520px', margin: '0 auto' }, editableProps: [{ key: 'orderNo', label: 'Order #', type: 'text' }, { key: 'currentStep', label: 'Current Step', type: 'number' }, { key: 'carrier', label: 'Carrier', type: 'text' }] },

  { name: 'Wishlist Grid', type: 'wishlist-grid', icon: '💜', category: 'commerce', description: 'Saved-items grid with move-to-cart', defaultProps: { heading: 'Your wishlist', columns: 3, moveLabel: 'Move to cart' }, defaultStyles: { padding: '1.5rem', maxWidth: '1000px', margin: '0 auto' }, editableProps: [{ key: 'heading', label: 'Heading', type: 'text' }, { key: 'columns', label: 'Columns', type: 'number' }] },

  { name: 'Reviews Summary', type: 'reviews-summary', icon: '⭐', category: 'commerce', description: 'Average rating + distribution bars', defaultProps: { average: 4.6, total: 218, bars: [{ stars: 5, pct: 72 }, { stars: 4, pct: 18 }, { stars: 3, pct: 6 }, { stars: 2, pct: 3 }, { stars: 1, pct: 1 }] }, defaultStyles: { display: 'flex', gap: '1.5rem', alignItems: 'center', padding: '1.25rem', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '560px' }, editableProps: [{ key: 'average', label: 'Average', type: 'number' }, { key: 'total', label: 'Total Reviews', type: 'number' }] },

  { name: 'Single Review Card', type: 'review-card', icon: '💬', category: 'commerce', description: 'One customer review with verified badge', defaultProps: { name: 'Priya S.', rating: 5, date: '2 days ago', title: 'Exactly as described', body: 'Quality exceeded expectations. Fast shipping too.', verified: true, avatar: '' }, defaultStyles: { padding: '1.1rem', borderRadius: '0.75rem', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '480px' }, editableProps: [{ key: 'name', label: 'Name', type: 'text' }, { key: 'title', label: 'Review Title', type: 'text' }, { key: 'body', label: 'Review Body', type: 'textarea' }, { key: 'rating', label: 'Stars', type: 'number' }, { key: 'verified', label: 'Verified Badge', type: 'toggle' }] },

  { name: 'Trust Badges Row', type: 'trust-badges-row', icon: '🛡️', category: 'commerce', description: 'Guarantees strip (shipping, returns, secure)', defaultProps: { badges: [{ icon: '🚚', text: 'Free shipping over $50' }, { icon: '↩️', text: '30-day returns' }, { icon: '🔒', text: 'Secure checkout' }] }, defaultStyles: { display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '1.5rem', padding: '1rem', borderTop: '1px solid rgba(255,255,255,0.08)' }, editableProps: [] },

];
