import type { BlockDefinition } from '../types';

export const FILES_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// FILES
// ═══════════════════════════════════════
  { name: 'Download Button', type: 'download-button', icon: '⬇️', category: 'files', description: 'File download button', defaultProps: { url: '#', label: 'Download', fileName: 'file.pdf', fileSize: '' }, defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.625rem 1.25rem', backgroundColor: '#7c3aed', color: '#ffffff', borderRadius: '0.5rem', fontWeight: '600', fontSize: '0.875rem', border: 'none', cursor: 'pointer', textDecoration: 'none' }, editableProps: [{ key: 'url', label: 'File URL', type: 'text' }, { key: 'label', label: 'Button Text', type: 'text' }, { key: 'fileName', label: 'File Name', type: 'text' }, { key: 'fileSize', label: 'File Size', type: 'text' }] },
  { name: 'ZIP Archive', type: 'zip-archive', icon: '📦', category: 'files', description: 'Multi-file ZIP download', defaultProps: { title: 'Download All Files', files: [{ name: 'file1.pdf', url: '#' }, { name: 'file2.pdf', url: '#' }, { name: 'file3.pdf', url: '#' }], buttonText: 'Download All (ZIP)' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }] },
  { name: 'Document Preview', type: 'doc-preview', icon: '📋', category: 'files', description: 'File preview card', defaultProps: { title: 'Document Title', type: 'PDF', size: '2.3 MB', url: '#', thumbnail: '', lastModified: '2025-01-15' }, defaultStyles: { display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)', cursor: 'pointer', maxWidth: '400px' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'type', label: 'File Type', type: 'text' }, { key: 'size', label: 'File Size', type: 'text' }, { key: 'url', label: 'File URL', type: 'text' }, { key: 'thumbnail', label: 'Thumbnail', type: 'image' }] },
  { name: 'Upload Progress', type: 'upload-progress', icon: '📤', category: 'files', description: 'Upload progress bar', defaultProps: { label: 'Uploading...', progress: 45, status: 'uploading', showPercentage: true, fileName: 'document.pdf' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '400px' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'progress', label: 'Progress (%)', type: 'number' }, { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Uploading', value: 'uploading' }, { label: 'Processing', value: 'processing' }, { label: 'Complete', value: 'complete' }, { label: 'Error', value: 'error' }] }, { key: 'showPercentage', label: 'Show %', type: 'toggle' }, { key: 'fileName', label: 'File Name', type: 'text' }] },
];
