import type { BlockDefinition } from '../types';

export const FORMS_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// FORMS
// ═══════════════════════════════════════
  { name: 'Button', type: 'button', icon: '🔘', category: 'forms', description: 'Single call-to-action button', defaultProps: { label: 'Click Here', url: '#', variant: 'primary', size: 'md' }, defaultStyles: { backgroundColor: '#7c3aed', color: '#ffffff', padding: '0.625rem 1.25rem', borderRadius: '0.5rem', fontWeight: '600', fontSize: '0.875rem', display: 'inline-block', border: 'none', textDecoration: 'none' }, editableProps: [{ key: 'label', label: 'Text', type: 'text' }, { key: 'url', label: 'URL', type: 'text' }, { key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Primary', value: 'primary' }, { label: 'Secondary', value: 'secondary' }, { label: 'Outline', value: 'outline' }, { label: 'Ghost', value: 'ghost' }, { label: 'Link', value: 'link' }] }, { key: 'size', label: 'Size', type: 'select', options: [{ label: 'Small', value: 'sm' }, { label: 'Medium', value: 'md' }, { label: 'Large', value: 'lg' }] }] },
  { name: 'Input', type: 'input', icon: '⌨️', category: 'forms', description: 'Single text input field', defaultProps: { label: 'Name', placeholder: 'Enter your name', type: 'text', required: false }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'type', label: 'Type', type: 'select', options: [{ label: 'Text', value: 'text' }, { label: 'Email', value: 'email' }, { label: 'Password', value: 'password' }, { label: 'Number', value: 'number' }, { label: 'Tel', value: 'tel' }, { label: 'URL', value: 'url' }] }, { key: 'required', label: 'Required', type: 'toggle' }] },
  { name: 'Textarea', type: 'textarea', icon: '📄', category: 'forms', description: 'Multi-line textarea', defaultProps: { label: 'Message', placeholder: 'Write your message...', rows: 4 }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'rows', label: 'Rows', type: 'number' }] },
  { name: 'Select', type: 'select', icon: '📑', category: 'forms', description: 'Dropdown select field', defaultProps: { label: 'Choose Option', options: ['Option 1', 'Option 2', 'Option 3'] }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }] },
  { name: 'Checkbox', type: 'checkbox', icon: '✅', category: 'forms', description: 'Single checkbox with label', defaultProps: { label: 'I agree to terms.', checked: false }, defaultStyles: { marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'checked', label: 'Default Checked', type: 'toggle' }] },
  { name: 'Radio', type: 'radio', icon: '🔘', category: 'forms', description: 'Radio button group', defaultProps: { label: 'Select Option', options: ['Option A', 'Option B', 'Option C'] }, defaultStyles: { marginBottom: '1rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }] },
  { name: 'Toggle', type: 'toggle', icon: '🔄', category: 'forms', description: 'On/off toggle switch', defaultProps: { label: 'Enable Feature', enabled: false }, defaultStyles: { marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'enabled', label: 'Default Enabled', type: 'toggle' }] },
  { name: 'Rating', type: 'rating', icon: '⭐', category: 'forms', description: 'Star rating input', defaultProps: { max: 5, value: 3, label: 'Rate your experience' }, defaultStyles: { marginBottom: '1rem', fontSize: '1.5rem', display: 'flex', gap: '0.25rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'max', label: 'Max Stars', type: 'range' }, { key: 'value', label: 'Default', type: 'range' }] },
  { name: 'File Upload', type: 'file-upload', icon: '📎', category: 'forms', description: 'File upload / drag-drop zone', defaultProps: { label: 'Upload Files', accept: 'image/*,.pdf', multiple: true, maxSize: '10MB' }, defaultStyles: { padding: '2rem', border: '2px dashed rgba(255,255,255,0.2)', borderRadius: '0.75rem', textAlign: 'center', marginBottom: '1rem', cursor: 'pointer' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'multiple', label: 'Multiple Files', type: 'toggle' }] },
  { name: 'Contact Form', type: 'contact-form', icon: '📧', category: 'forms', description: 'Full contact form', defaultProps: { fields: ['name', 'email', 'message'], submitText: 'Send Message', showSubject: true }, defaultStyles: { maxWidth: '600px', margin: '0 auto', padding: '1.5rem' }, editableProps: [{ key: 'submitText', label: 'Submit Text', type: 'text' }, { key: 'showSubject', label: 'Show Subject', type: 'toggle' }] },
  { name: 'Newsletter', type: 'newsletter', icon: '📰', category: 'forms', description: 'Email signup form', defaultProps: { title: 'Stay Updated', placeholder: 'your@email.com', buttonText: 'Subscribe', service: 'mailchimp' }, defaultStyles: { padding: '2rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', textAlign: 'center', maxWidth: '500px', margin: '0 auto' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }, { key: 'service', label: 'Service', type: 'select', options: [{ label: 'Mailchimp', value: 'mailchimp' }, { label: 'ConvertKit', value: 'convertkit' }, { label: 'SendGrid', value: 'sendgrid' }, { label: 'Custom', value: 'custom' }] }] },
  { name: 'Search', type: 'search', icon: '🔍', category: 'forms', description: 'Search field with icon', defaultProps: { placeholder: 'Search...', buttonText: '🔍', showButton: true }, defaultStyles: { display: 'flex', gap: '0.5rem', maxWidth: '400px', marginBottom: '1rem' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'showButton', label: 'Show Button', type: 'toggle' }] },
  { name: 'WP Search', type: 'wp-search', icon: '🔍', category: 'forms', description: 'WP search form', defaultProps: { placeholder: 'Search...', buttonText: 'Search' }, defaultStyles: { padding: '1rem' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }] },
  { name: 'Form to Webhook', type: 'form-webhook', icon: '📋', category: 'forms', description: 'Form that submits to webhook', defaultProps: { webhookUrl: '', method: 'POST', fields: ['name', 'email', 'message'], successMessage: 'Thanks! We will be in touch.' }, defaultStyles: { maxWidth: '500px', margin: '0 auto', padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem' }, editableProps: [{ key: 'webhookUrl', label: 'Webhook URL', type: 'text' }, { key: 'successMessage', label: 'Success Message', type: 'text' }] },
  { name: 'AI Form Builder', type: 'ai-form', icon: '📋', category: 'forms', description: 'Generate forms from description', defaultProps: { description: 'Create a contact form with name, email, and message fields.', fields: [] }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(245,158,11,0.08)', borderRadius: '0.75rem', border: '1px solid rgba(245,158,11,0.2)' }, editableProps: [{ key: 'description', label: 'Form Description', type: 'textarea' }] },
  { name: 'Date Picker', type: 'date-picker', icon: '📅', category: 'forms', description: 'Calendar date selection input', defaultProps: { label: 'Select Date', format: 'YYYY-MM-DD', minDate: '', maxDate: '' }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'format', label: 'Format', type: 'select', options: [{ label: 'YYYY-MM-DD', value: 'YYYY-MM-DD' }, { label: 'MM/DD/YYYY', value: 'MM/DD/YYYY' }, { label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' }] }] },
  { name: 'Color Picker', type: 'color-picker', icon: '🎨', category: 'forms', description: 'Color selection input', defaultProps: { label: 'Pick a Color', value: '#7c3aed' }, defaultStyles: { marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'value', label: 'Default Color', type: 'color' }] },
  { name: 'Slider', type: 'slider', icon: '🎚️', category: 'forms', description: 'Range slider with value display', defaultProps: { label: 'Volume', min: 0, max: 100, step: 1, value: 50 }, defaultStyles: { marginBottom: '1rem', width: '100%', display: 'flex', flexDirection: 'column', gap: '0.25rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'min', label: 'Min', type: 'number' }, { key: 'max', label: 'Max', type: 'number' }, { key: 'step', label: 'Step', type: 'number' }, { key: 'value', label: 'Default', type: 'number' }] },
  { name: 'Multi-Step Form', type: 'form-multi-step', icon: '🪜', category: 'forms', description: 'Wizard-style form with progress steps', defaultProps: { steps: ['Account', 'Details', 'Confirm'], currentStep: 1, showProgress: true }, defaultStyles: { padding: '1.5rem', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '520px', margin: '0 auto' }, editableProps: [{ key: 'currentStep', label: 'Active Step', type: 'number' }, { key: 'showProgress', label: 'Show Progress', type: 'toggle' }] },
  { name: 'NPS Survey', type: 'survey-nps', icon: '📊', category: 'forms', description: 'Net Promoter Score 0-10 selector', defaultProps: { question: 'How likely are you to recommend us?', lowLabel: 'Not likely', highLabel: 'Very likely' }, defaultStyles: { textAlign: 'center', padding: '1.25rem', borderRadius: '0.75rem', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'question', label: 'Question', type: 'textarea' }, { key: 'lowLabel', label: 'Low Label', type: 'text' }, { key: 'highLabel', label: 'High Label', type: 'text' }] },
  { name: 'Quiz Form', type: 'quiz-form', icon: '🎯', category: 'forms', description: 'Interactive quiz with options', defaultProps: { question: 'Which plan fits you?', options: [{ text: 'Solo builder', points: 1 }, { text: 'Team of 3-10', points: 2 }, { text: 'Agency', points: 3 }], resultNote: '' }, defaultStyles: { padding: '1.5rem', borderRadius: '0.75rem', border: '1px solid rgba(168,85,247,0.3)', maxWidth: '520px' }, editableProps: [{ key: 'question', label: 'Question', type: 'text' }, { key: 'resultNote', label: 'Result Note', type: 'textarea' }] },
  { name: 'Booking Form', type: 'booking-form', icon: '🗓️', category: 'forms', description: 'Date/time booking with service select', defaultProps: { service: '30-min intro call', date: '', timeSlots: ['09:00', '11:00', '14:00'], timezone: 'UTC', cta: 'Book slot' }, defaultStyles: { display: 'grid', gap: '0.75rem', padding: '1.5rem', borderRadius: '0.75rem', backgroundColor: 'rgba(34,197,94,0.05)', border: '1px solid rgba(34,197,94,0.25)', maxWidth: '440px' }, editableProps: [{ key: 'service', label: 'Service Name', type: 'text' }, { key: 'timezone', label: 'Timezone Label', type: 'text' }, { key: 'cta', label: 'Button Text', type: 'text' }] },
  { name: 'Login Form', type: 'login-form', icon: '🔐', category: 'auth', description: 'Email + password sign-in card', defaultProps: { heading: 'Welcome back', emailPlaceholder: 'you@example.com', buttonLabel: 'Sign in', showForgot: true, oauthButtons: [] }, defaultStyles: { display: 'grid', gap: '0.75rem', padding: '1.5rem', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '380px', margin: '0 auto' }, editableProps: [{ key: 'heading', label: 'Heading', type: 'text' }, { key: 'buttonLabel', label: 'Button Text', type: 'text' }, { key: 'showForgot', label: 'Forgot Link', type: 'toggle' }] },
  { name: 'Register Form', type: 'register-form', icon: '📝', category: 'auth', description: 'Sign-up card with password rules', defaultProps: { heading: 'Create account', passwordHint: 'Min 8 characters', requireTerms: true, termsLabel: 'I agree to the Terms' }, defaultStyles: { display: 'grid', gap: '0.75rem', padding: '1.5rem', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '400px', margin: '0 auto' }, editableProps: [{ key: 'heading', label: 'Heading', type: 'text' }, { key: 'passwordHint', label: 'Password Hint', type: 'text' }, { key: 'termsLabel', label: 'Terms Label', type: 'text' }, { key: 'requireTerms', label: 'Require Terms', type: 'toggle' }] },
  { name: 'OTP Input', type: 'otp-input', icon: '🔢', category: 'auth', description: 'One-time code entry with auto-advance', defaultProps: { digits: 6, resendAfter: 30, masked: false }, defaultStyles: { display: 'flex', justifyContent: 'center', gap: '0.5rem', padding: '1rem' }, editableProps: [{ key: 'digits', label: 'Digit Count', type: 'number' }, { key: 'resendAfter', label: 'Resend (s)', type: 'number' }, { key: 'masked', label: 'Mask Input', type: 'toggle' }] },
  { name: 'Profile Edit Form', type: 'profile-edit-form', icon: '👤', category: 'forms', description: 'Avatar + name/bio edit layout', defaultProps: { fields: [{ key: 'name', label: 'Full Name' }, { key: 'bio', label: 'Bio' }], avatarUrl: '', saveLabel: 'Save profile' }, defaultStyles: { display: 'flex', gap: '1.25rem', alignItems: 'start', padding: '1.5rem', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '560px' }, editableProps: [{ key: 'saveLabel', label: 'Save Button', type: 'text' }] },
  { name: 'Filter Panel', type: 'filter-panel', icon: '🎛️', category: 'forms', description: 'Sidebar filters for grids/search', defaultProps: { filters: [{ label: 'Category', type: 'checkbox', options: ['SaaS', 'Agency', 'Shop'] }, { label: 'Price', type: 'range' }], applyLabel: 'Apply' }, defaultStyles: { display: 'grid', gap: '1rem', padding: '1.25rem', borderRadius: '0.75rem', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.1)', width: '260px' }, editableProps: [{ key: 'applyLabel', label: 'Apply Button', type: 'text' }] },
  { name: 'Rating Feedback', type: 'rating-feedback', icon: '⭐', category: 'forms', description: 'Star rating with optional comment', defaultProps: { maxStars: 5, askComment: true, commentPlaceholder: 'Tell us more…', submitLabel: 'Send feedback' }, defaultStyles: { textAlign: 'center', padding: '1.25rem', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '420px' }, editableProps: [{ key: 'maxStars', label: 'Max Stars', type: 'number' }, { key: 'askComment', label: 'Ask Comment', type: 'toggle' }, { key: 'submitLabel', label: 'Submit Text', type: 'text' }] },
  { name: 'File Upload Field', type: 'file-upload-form', icon: '📎', category: 'files', description: 'Drag-drop upload with file list', defaultProps: { accept: '.pdf,.png,.jpg', maxFiles: 3, maxSizeMb: 10, dropText: 'Drop files or click' }, defaultStyles: { padding: '2rem', textAlign: 'center', border: '2px dashed rgba(255,255,255,0.15)', borderRadius: '0.75rem', cursor: 'pointer' }, editableProps: [{ key: 'accept', label: 'Accept Types', type: 'text' }, { key: 'maxFiles', label: 'Max Files', type: 'number' }, { key: 'maxSizeMb', label: 'Max Size (MB)', type: 'number' }, { key: 'dropText', label: 'Drop Text', type: 'text' }] },
  { name: 'Inline Newsletter', type: 'newsletter-inline', icon: '✉️', category: 'marketing', description: 'Single-line email capture', defaultProps: { placeholder: 'Enter your email', buttonLabel: 'Subscribe', successNote: 'Check your inbox!', disclaimer: 'No spam. Unsubscribe anytime.' }, defaultStyles: { display: 'flex', gap: '0.5rem', padding: '0.75rem', borderRadius: '0.6rem', backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.12)', maxWidth: '480px', margin: '0 auto', flexWrap: 'wrap' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'buttonLabel', label: 'Button Text', type: 'text' }, { key: 'successNote', label: 'Success Note', type: 'text' }, { key: 'disclaimer', label: 'Disclaimer', type: 'text' }] },
];
