import type { BlockDefinition } from '../types';

export const FORMS_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// FORMS
// ═══════════════════════════════════════
  { name: 'Button', type: 'button', icon: '🔘', category: 'forms', description: 'Single call-to-action button', defaultProps: { label: 'Click Here', url: '#', variant: 'primary', size: 'md' }, defaultStyles: { backgroundColor: '#7c3aed', color: '#ffffff', padding: '0.625rem 1.25rem', borderRadius: '0.5rem', fontWeight: '600', fontSize: '0.875rem', display: 'inline-block', border: 'none', textDecoration: 'none' }, editableProps: [{ key: 'label', label: 'Text', type: 'text' }, { key: 'url', label: 'URL', type: 'text' }, { key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Primary', value: 'primary' }, { label: 'Secondary', value: 'secondary' }, { label: 'Outline', value: 'outline' }, { label: 'Ghost', value: 'ghost' }, { label: 'Link', value: 'link' }] }, { key: 'size', label: 'Size', type: 'select', options: [{ label: 'Small', value: 'sm' }, { label: 'Medium', value: 'md' }, { label: 'Large', value: 'lg' }] }] },
  { name: 'Input', type: 'input', icon: '⌨️', category: 'forms', description: 'Single text input field', defaultProps: { label: 'Name', placeholder: 'Enter your name', type: 'text', required: false }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'type', label: 'Type', type: 'select', options: [{ label: 'Text', value: 'text' }, { label: 'Email', value: 'email' }, { label: 'Password', value: 'password' }, { label: 'Number', value: 'number' }, { label: 'Tel', value: 'tel' }, { label: 'URL', value: 'url' }] }, { key: 'required', label: 'Required', type: 'toggle' }] },
  { name: 'Textarea', type: 'textarea', icon: '📄', category: 'forms', description: 'Multi-line textarea', defaultProps: { label: 'Message', placeholder: 'Write your message...', rows: 4 }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'rows', label: 'Rows', type: 'number' }] },
  { name: 'Select', type: 'select', icon: '📑', category: 'forms', description: 'Dropdown select field', defaultProps: { label: 'Choose Option', options: ['Option 1', 'Option 2', 'Option 3'] }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }] },
  { name: 'Checkbox', type: 'checkbox', icon: '✅', category: 'forms', description: 'Single checkbox with label', defaultProps: { label: 'I agree to terms.', checked: false }, defaultStyles: { marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'checked', label: 'Default Checked', type: 'toggle' }] },
  { name: 'Radio', type: 'radio', icon: '🔘', category: 'forms', description: 'Radio button group', defaultProps: { label: 'Select Option', options: ['Option A', 'Option B', 'Option C'] }, defaultStyles: { marginBottom: '1rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }] },
  { name: 'Toggle', type: 'toggle', icon: '🔄', category: 'forms', description: 'On/off toggle switch', defaultProps: { label: 'Enable Feature', enabled: false }, defaultStyles: { marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'enabled', label: 'Default Enabled', type: 'toggle' }] },
  { name: 'Rating', type: 'rating', icon: '⭐', category: 'forms', description: 'Star rating input', defaultProps: { max: 5, value: 3, label: 'Rate your experience' }, defaultStyles: { marginBottom: '1rem', fontSize: '1.5rem', display: 'flex', gap: '0.25rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'max', label: 'Max Stars', type: 'range' }, { key: 'value', label: 'Default', type: 'range' }] },
  { name: 'File Upload', type: 'file-upload', icon: '📎', category: 'forms', description: 'File upload / drag-drop zone', defaultProps: { label: 'Upload Files', accept: 'image/*,.pdf', multiple: true, maxSize: '10MB' }, defaultStyles: { padding: '2rem', border: '2px dashed rgba(255,255,255,0.2)', borderRadius: '0.75rem', textAlign: 'center', marginBottom: '1rem', cursor: 'pointer' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'multiple', label: 'Multiple Files', type: 'toggle' }] },
  { name: 'Contact Form', type: 'contact-form', icon: '📧', category: 'forms', description: 'Full contact form', defaultProps: { fields: ['name', 'email', 'message'], submitText: 'Send Message', showSubject: true }, defaultStyles: { maxWidth: '600px', margin: '0 auto', padding: '1.5rem' }, editableProps: [{ key: 'submitText', label: 'Submit Text', type: 'text' }, { key: 'showSubject', label: 'Show Subject', type: 'toggle' }] },
  { name: 'Newsletter', type: 'newsletter', icon: '📰', category: 'forms', description: 'Email signup form', defaultProps: { title: 'Stay Updated', placeholder: 'your@email.com', buttonText: 'Subscribe', service: 'mailchimp' }, defaultStyles: { padding: '2rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', textAlign: 'center', maxWidth: '500px', margin: '0 auto' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }, { key: 'service', label: 'Service', type: 'select', options: [{ label: 'Mailchimp', value: 'mailchimp' }, { label: 'ConvertKit', value: 'convertkit' }, { label: 'SendGrid', value: 'sendgrid' }, { label: 'Custom', value: 'custom' }] }] },
  { name: 'Search', type: 'search', icon: '🔍', category: 'forms', description: 'Search field with icon', defaultProps: { placeholder: 'Search...', buttonText: '🔍', showButton: true }, defaultStyles: { display: 'flex', gap: '0.5rem', maxWidth: '400px', marginBottom: '1rem' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'showButton', label: 'Show Button', type: 'toggle' }] },
  { name: 'WP Search', type: 'wp-search', icon: '🔍', category: 'forms', description: 'WP search form', defaultProps: { placeholder: 'Search...', buttonText: 'Search' }, defaultStyles: { padding: '1rem' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }] },
  { name: 'Form to Webhook', type: 'form-webhook', icon: '📋', category: 'forms', description: 'Form that submits to webhook', defaultProps: { webhookUrl: '', method: 'POST', fields: ['name', 'email', 'message'], successMessage: 'Thanks! We will be in touch.' }, defaultStyles: { maxWidth: '500px', margin: '0 auto', padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem' }, editableProps: [{ key: 'webhookUrl', label: 'Webhook URL', type: 'text' }, { key: 'successMessage', label: 'Success Message', type: 'text' }] },
  { name: 'AI Form Builder', type: 'ai-form', icon: '📋', category: 'forms', description: 'Generate forms from description', defaultProps: { description: 'Create a contact form with name, email, and message fields.', fields: [] }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(245,158,11,0.08)', borderRadius: '0.75rem', border: '1px solid rgba(245,158,11,0.2)' }, editableProps: [{ key: 'description', label: 'Form Description', type: 'textarea' }] },
  { name: 'Date Picker', type: 'date-picker', icon: '📅', category: 'forms', description: 'Calendar date selection input', defaultProps: { label: 'Select Date', format: 'YYYY-MM-DD', minDate: '', maxDate: '' }, defaultStyles: { marginBottom: '1rem', width: '100%' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'format', label: 'Format', type: 'select', options: [{ label: 'YYYY-MM-DD', value: 'YYYY-MM-DD' }, { label: 'MM/DD/YYYY', value: 'MM/DD/YYYY' }, { label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' }] }] },
  { name: 'Color Picker', type: 'color-picker', icon: '🎨', category: 'forms', description: 'Color selection input', defaultProps: { label: 'Pick a Color', value: '#7c3aed' }, defaultStyles: { marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'value', label: 'Default Color', type: 'color' }] },
  { name: 'Slider', type: 'slider', icon: '🎚️', category: 'forms', description: 'Range slider with value display', defaultProps: { label: 'Volume', min: 0, max: 100, step: 1, value: 50 }, defaultStyles: { marginBottom: '1rem', width: '100%', display: 'flex', flexDirection: 'column', gap: '0.25rem' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'min', label: 'Min', type: 'number' }, { key: 'max', label: 'Max', type: 'number' }, { key: 'step', label: 'Step', type: 'number' }, { key: 'value', label: 'Default', type: 'number' }] },
];
