import type { BlockDefinition } from '../types';

// Curated list of block types that make sense as children of a layout container
// (content, media, interactive, nested-layout). Blocks not listed are rejected
// by the drop-gate in VisualBuilderCanvas.handleDrop. Empty/omitted allowedChildren
// on a container = accept all (fully backward-compatible).
export const ALLOWED_CONTAINER_CHILDREN = [
  'heading', 'paragraph', 'rich-text', 'text', 'image', 'video', 'audio',
  'button', 'card', 'spacer', 'divider', 'separator', 'icon', 'badge', 'list',
  'quote', 'code', 'preformatted', 'cover', 'gallery', 'stats-section',
  'hero', 'cta', 'testimonial', 'feature-grid', 'logo-cloud', 'team-grid',
  'columns', 'row', 'group', 'section', 'container', 'grid', 'flex',
  'sidebar-layout', 'hero-layout', 'masonry', 'wrapper', 'stack', 'accordion',
  'tabs', 'modal', 'overlay', 'tabs-container',
];

export const LAYOUT_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// LAYOUT
// ═══════════════════════════════════════
  { name: 'Columns', type: 'columns', icon: '🔲', category: 'layout', description: 'Multi-column grid layout', defaultProps: { columns: 2 }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'columns', label: 'Count', type: 'range' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Row', type: 'row', icon: '➡️', category: 'layout', description: 'Horizontal flex row', defaultProps: { gap: '1rem', alignItems: 'center' }, defaultStyles: { display: 'flex', flexDirection: 'row', gap: '1rem', alignItems: 'center', marginBottom: '1rem' }, editableProps: [{ key: 'gap', label: 'Gap', type: 'text' }, { key: 'alignItems', label: 'Align', type: 'select', options: [{ label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }, { label: 'Stretch', value: 'stretch' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Group', type: 'group', icon: '📦', category: 'layout', description: 'Container for nesting blocks', defaultProps: {}, defaultStyles: { padding: '1rem', marginBottom: '1rem' }, editableProps: [], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Section', type: 'section', icon: '📐', category: 'layout', description: 'Full-width section wrapper', defaultProps: { width: 'full', paddingY: '4rem' }, defaultStyles: { padding: '4rem 2rem', marginBottom: '1rem' }, editableProps: [{ key: 'paddingY', label: 'Padding Y', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Container', type: 'container', icon: '🗃️', category: 'layout', description: 'Max-width centered container', defaultProps: { maxWidth: '1200px' }, defaultStyles: { maxWidth: '1200px', margin: '0 auto', padding: '0 1rem' }, editableProps: [{ key: 'maxWidth', label: 'Max Width', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Grid', type: 'grid', icon: '🔳', category: 'layout', description: 'CSS Grid layout container', defaultProps: { columns: 3, gap: '1rem' }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'number' }, { key: 'gap', label: 'Gap', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Flex', type: 'flex', icon: '➰', category: 'layout', description: 'Flexbox layout container', defaultProps: { direction: 'row', wrap: 'wrap', gap: '1rem', justify: 'center' }, defaultStyles: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: '1rem', justifyContent: 'center' }, editableProps: [{ key: 'direction', label: 'Direction', type: 'select', options: [{ label: 'Row', value: 'row' }, { label: 'Column', value: 'column' }] }, { key: 'justify', label: 'Justify', type: 'select', options: [{ label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }, { label: 'Space Between', value: 'space-between' }, { label: 'Space Around', value: 'space-around' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Wrapper', type: 'wrapper', icon: '📦', category: 'layout', description: 'Generic wrapper with max-width constraint', defaultProps: { maxWidth: '1200px', padding: '1rem' }, defaultStyles: { maxWidth: '1200px', margin: '0 auto', padding: '1rem' }, editableProps: [{ key: 'maxWidth', label: 'Max Width', type: 'text' }, { key: 'padding', label: 'Padding', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Stack', type: 'stack', icon: '📚', category: 'layout', description: 'Vertical stack layout with consistent gap', defaultProps: { gap: '1rem', alignItems: 'stretch' }, defaultStyles: { display: 'flex', flexDirection: 'column', gap: '1rem', alignItems: 'stretch' }, editableProps: [{ key: 'gap', label: 'Gap', type: 'text' }, { key: 'alignItems', label: 'Align', type: 'select', options: [{ label: 'Stretch', value: 'stretch' }, { label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Sidebar Layout', type: 'sidebar-layout', icon: '📐', category: 'layout', description: 'Content + sidebar layout', defaultProps: { sidebarWidth: '300px', sidebarPosition: 'right', gap: '2rem' }, defaultStyles: { display: 'grid', gridTemplateColumns: '1fr 300px', gap: '2rem', alignItems: 'start' }, editableProps: [{ key: 'sidebarWidth', label: 'Sidebar Width', type: 'text' }, { key: 'sidebarPosition', label: 'Sidebar Position', type: 'select', options: [{ label: 'Right', value: 'right' }, { label: 'Left', value: 'left' }] }, { key: 'gap', label: 'Gap', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Hero Layout', type: 'hero-layout', icon: '🦸', category: 'layout', description: 'Hero section structure', defaultProps: { height: '80vh', overlay: 'rgba(0,0,0,0.3)', align: 'center' }, defaultStyles: { display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', minHeight: '80vh', padding: '2rem', position: 'relative', textAlign: 'center' }, editableProps: [{ key: 'height', label: 'Min Height', type: 'text' }, { key: 'overlay', label: 'Overlay', type: 'color' }, { key: 'align', label: 'Align', type: 'select', options: [{ label: 'Center', value: 'center' }, { label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Masonry', type: 'masonry', icon: '🧱', category: 'layout', description: 'Masonry grid layout', defaultProps: { columns: 3, gap: '1rem' }, defaultStyles: { columns: '3', columnGap: '1rem', marginBottom: '1rem' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'range' }, { key: 'gap', label: 'Gap', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Tabs Section', type: 'tabs-section', icon: '🗂️', category: 'layout', description: 'Tabbed content panels', defaultProps: { tabs: [{ label: 'Overview' }, { label: 'Features' }, { label: 'Pricing' }], active: 0, variant: 'underline' }, defaultStyles: { padding: '1.5rem', maxWidth: '900px', margin: '0 auto' }, editableProps: [{ key: 'active', label: 'Active Tab', type: 'number' }, { key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Underline', value: 'underline' }, { label: 'Pills', value: 'pills' }] }] },
  { name: 'Accordion Section', type: 'accordion-section', icon: '📚', category: 'layout', description: 'Stacked expand/collapse rows', defaultProps: { items: [{ title: 'Getting started', content: 'Drag your first block onto the canvas.' }], singleOpen: true }, defaultStyles: { display: 'grid', gap: '0.5rem', padding: '1.5rem', maxWidth: '760px', margin: '0 auto' }, editableProps: [{ key: 'singleOpen', label: 'Single Open Only', type: 'toggle' }] },
  { name: 'Modal Trigger', type: 'modal-trigger', icon: '🪟', category: 'layout', description: 'Button that opens a modal panel', defaultProps: { buttonLabel: 'Open dialog', modalTitle: 'Hello!', modalBody: 'This is a modal built with Wonderland blocks.', width: '480px' }, defaultStyles: {}, editableProps: [{ key: 'buttonLabel', label: 'Button Text', type: 'text' }, { key: 'modalTitle', label: 'Modal Title', type: 'text' }, { key: 'modalBody', label: 'Modal Body', type: 'textarea' }, { key: 'width', label: 'Modal Width', type: 'text' }] },
  { name: 'Sticky CTA Bar', type: 'sticky-cta-bar', icon: '📌', category: 'layout', description: 'Bar pinned to viewport bottom', defaultProps: { text: 'Ready to build?', cta: 'Start free', href: '/subscription', position: 'bottom', dismissible: false }, defaultStyles: { position: 'sticky', bottom: '0', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem', padding: '0.75rem 1.25rem', backgroundColor: '#111827', borderTop: '1px solid rgba(255,255,255,0.12)', zIndex: '50' }, editableProps: [{ key: 'text', label: 'Text', type: 'text' }, { key: 'cta', label: 'Button Text', type: 'text' }, { key: 'href', label: 'Link', type: 'text' }, { key: 'position', label: 'Position', type: 'select', options: [{ label: 'Bottom', value: 'bottom' }, { label: 'Top', value: 'top' }] }] },
  { name: 'Split Screen', type: 'split-screen', icon: '🪓', category: 'layout', description: 'Two-panel side-by-side section', defaultProps: { ratio: '1fr 1fr', gap: '2rem', stackOnMobile: true, minHeight: '380px' }, defaultStyles: { display: 'flex', flexWrap: 'wrap', gap: '2rem', padding: '2rem', maxWidth: '1200px', margin: '0 auto' }, allowedChildren: ['*'], editableProps: [{ key: 'ratio', label: 'Column Ratio', type: 'text' }, { key: 'gap', label: 'Gap', type: 'text' }] },
  { name: 'Masonry Grid', type: 'masonry-grid', icon: '🧱', category: 'layout', description: 'Pinterest-style variable-height grid', defaultProps: { columns: 3, gap: '1rem' }, defaultStyles: { columnCount: 3, columnGap: '1rem', padding: '1.5rem', maxWidth: '1100px', margin: '0 auto' }, allowedChildren: ['*'], editableProps: [{ key: 'columns', label: 'Columns', type: 'number' }, { key: 'gap', label: 'Gap', type: 'text' }] },
  { name: 'Spacer', type: 'spacer-block', icon: '↕️', category: 'layout', description: 'Vertical spacing control', defaultProps: { height: 64, showGuides: false }, defaultStyles: {}, editableProps: [{ key: 'height', label: 'Height (px)', type: 'number' }, { key: 'showGuides', label: 'Show Guides', type: 'toggle' }] },
  { name: 'Styled Divider', type: 'divider-styled', icon: '➖', category: 'layout', description: 'Decorative divider with center label', defaultProps: { label: '', style: 'gradient', thickness: 2 }, defaultStyles: { display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem 0', maxWidth: '800px', margin: '0 auto' }, editableProps: [{ key: 'label', label: 'Center Label', type: 'text' }, { key: 'thickness', label: 'Thickness (px)', type: 'number' }] },
  { name: 'Bento Grid', type: 'bento-grid', icon: '🍱', category: 'layout', description: 'Modern mixed-size feature grid', defaultProps: { columns: 4, tiles: [{ span: 2, title: 'Ship faster' }, { title: 'AI inside' }, { title: 'Realtime' }, { span: 2, title: 'Deploy anywhere' }], gap: '0.75rem' }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '0.75rem', padding: '2rem', maxWidth: '1000px', margin: '0 auto' }, editableProps: [{ key: 'columns', label: 'Grid Columns', type: 'number' }, { key: 'gap', label: 'Gap', type: 'text' }] },
  { name: 'Hero Split', type: 'hero-split', icon: '🎯', category: 'layout', description: 'Headline left, media right hero', defaultProps: { eyebrow: 'NEW', headline: 'Build at the speed of thought', sub: 'Prompt to production in one flow.', ctaPrimary: 'Start building', hrefPrimary: '/wonder-build/builder', imageUrl: '', flip: false }, defaultStyles: { display: 'grid', gridTemplateColumns: '1.1fr 1fr', alignItems: 'center', gap: '2.5rem', padding: '3rem', maxWidth: '1150px', margin: '0 auto' }, editableProps: [{ key: 'eyebrow', label: 'Eyebrow', type: 'text' }, { key: 'headline', label: 'Headline', type: 'textarea' }, { key: 'sub', label: 'Subheading', type: 'textarea' }, { key: 'ctaPrimary', label: 'CTA Text', type: 'text' }, { key: 'hrefPrimary', label: 'CTA Link', type: 'text' }, { key: 'imageUrl', label: 'Image', type: 'image' }, { key: 'flip', label: 'Flip Sides', type: 'toggle' }] },
  { name: 'Section Columns', type: 'section-columns', icon: '📐', category: 'layout', description: 'Generic N-column layout container', defaultProps: { columns: 3, gap: '1.25rem', align: 'stretch' }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1.25rem', padding: '1.5rem' }, allowedChildren: ['*'], editableProps: [{ key: 'columns', label: 'Columns', type: 'number' }, { key: 'align', label: 'Align Items', type: 'select', options: [{ label: 'Stretch', value: 'stretch' }, { label: 'Start', value: 'start' }, { label: 'Center', value: 'center' }] }] },
  { name: 'Scroll Container', type: 'scroll-container', icon: '📜', category: 'layout', description: 'Fixed-height scrollable area', defaultProps: { maxHeightPx: 320, direction: 'vertical', fadeEdges: true }, defaultStyles: { overflowY: 'auto', padding: '1rem', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '0.75rem' }, allowedChildren: ['*'], editableProps: [{ key: 'maxHeightPx', label: 'Max Height (px)', type: 'number' }, { key: 'fadeEdges', label: 'Fade Edges', type: 'toggle' }] },
];
