import type { BlockDefinition } from '../types';

// Curated list of block types that make sense as children of a layout container
// (content, media, interactive, nested-layout). Blocks not listed are rejected
// by the drop-gate in VisualBuilderCanvas.handleDrop. Empty/omitted allowedChildren
// on a container = accept all (fully backward-compatible).
export const ALLOWED_CONTAINER_CHILDREN = [
  'heading', 'paragraph', 'rich-text', 'text', 'image', 'video', 'audio',
  'button', 'card', 'spacer', 'divider', 'separator', 'icon', 'badge', 'list',
  'quote', 'code', 'preformatted', 'cover', 'gallery', 'stats-section',
  'hero', 'cta', 'testimonial', 'feature-grid', 'logo-cloud', 'team-grid',
  'columns', 'row', 'group', 'section', 'container', 'grid', 'flex',
  'sidebar-layout', 'hero-layout', 'masonry', 'wrapper', 'stack', 'accordion',
  'tabs', 'modal', 'overlay', 'tabs-container',
];

export const LAYOUT_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// LAYOUT
// ═══════════════════════════════════════
  { name: 'Columns', type: 'columns', icon: '🔲', category: 'layout', description: 'Multi-column grid layout', defaultProps: { columns: 2 }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'columns', label: 'Count', type: 'range' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Row', type: 'row', icon: '➡️', category: 'layout', description: 'Horizontal flex row', defaultProps: { gap: '1rem', alignItems: 'center' }, defaultStyles: { display: 'flex', flexDirection: 'row', gap: '1rem', alignItems: 'center', marginBottom: '1rem' }, editableProps: [{ key: 'gap', label: 'Gap', type: 'text' }, { key: 'alignItems', label: 'Align', type: 'select', options: [{ label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }, { label: 'Stretch', value: 'stretch' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Group', type: 'group', icon: '📦', category: 'layout', description: 'Container for nesting blocks', defaultProps: {}, defaultStyles: { padding: '1rem', marginBottom: '1rem' }, editableProps: [], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Section', type: 'section', icon: '📐', category: 'layout', description: 'Full-width section wrapper', defaultProps: { width: 'full', paddingY: '4rem' }, defaultStyles: { padding: '4rem 2rem', marginBottom: '1rem' }, editableProps: [{ key: 'paddingY', label: 'Padding Y', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Container', type: 'container', icon: '🗃️', category: 'layout', description: 'Max-width centered container', defaultProps: { maxWidth: '1200px' }, defaultStyles: { maxWidth: '1200px', margin: '0 auto', padding: '0 1rem' }, editableProps: [{ key: 'maxWidth', label: 'Max Width', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Grid', type: 'grid', icon: '🔳', category: 'layout', description: 'CSS Grid layout container', defaultProps: { columns: 3, gap: '1rem' }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'number' }, { key: 'gap', label: 'Gap', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Flex', type: 'flex', icon: '➰', category: 'layout', description: 'Flexbox layout container', defaultProps: { direction: 'row', wrap: 'wrap', gap: '1rem', justify: 'center' }, defaultStyles: { display: 'flex', flexDirection: 'row', flexWrap: 'wrap', gap: '1rem', justifyContent: 'center' }, editableProps: [{ key: 'direction', label: 'Direction', type: 'select', options: [{ label: 'Row', value: 'row' }, { label: 'Column', value: 'column' }] }, { key: 'justify', label: 'Justify', type: 'select', options: [{ label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }, { label: 'Space Between', value: 'space-between' }, { label: 'Space Around', value: 'space-around' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Wrapper', type: 'wrapper', icon: '📦', category: 'layout', description: 'Generic wrapper with max-width constraint', defaultProps: { maxWidth: '1200px', padding: '1rem' }, defaultStyles: { maxWidth: '1200px', margin: '0 auto', padding: '1rem' }, editableProps: [{ key: 'maxWidth', label: 'Max Width', type: 'text' }, { key: 'padding', label: 'Padding', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Stack', type: 'stack', icon: '📚', category: 'layout', description: 'Vertical stack layout with consistent gap', defaultProps: { gap: '1rem', alignItems: 'stretch' }, defaultStyles: { display: 'flex', flexDirection: 'column', gap: '1rem', alignItems: 'stretch' }, editableProps: [{ key: 'gap', label: 'Gap', type: 'text' }, { key: 'alignItems', label: 'Align', type: 'select', options: [{ label: 'Stretch', value: 'stretch' }, { label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Sidebar Layout', type: 'sidebar-layout', icon: '📐', category: 'layout', description: 'Content + sidebar layout', defaultProps: { sidebarWidth: '300px', sidebarPosition: 'right', gap: '2rem' }, defaultStyles: { display: 'grid', gridTemplateColumns: '1fr 300px', gap: '2rem', alignItems: 'start' }, editableProps: [{ key: 'sidebarWidth', label: 'Sidebar Width', type: 'text' }, { key: 'sidebarPosition', label: 'Sidebar Position', type: 'select', options: [{ label: 'Right', value: 'right' }, { label: 'Left', value: 'left' }] }, { key: 'gap', label: 'Gap', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Hero Layout', type: 'hero-layout', icon: '🦸', category: 'layout', description: 'Hero section structure', defaultProps: { height: '80vh', overlay: 'rgba(0,0,0,0.3)', align: 'center' }, defaultStyles: { display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', minHeight: '80vh', padding: '2rem', position: 'relative', textAlign: 'center' }, editableProps: [{ key: 'height', label: 'Min Height', type: 'text' }, { key: 'overlay', label: 'Overlay', type: 'color' }, { key: 'align', label: 'Align', type: 'select', options: [{ label: 'Center', value: 'center' }, { label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
  { name: 'Masonry', type: 'masonry', icon: '🧱', category: 'layout', description: 'Masonry grid layout', defaultProps: { columns: 3, gap: '1rem' }, defaultStyles: { columns: '3', columnGap: '1rem', marginBottom: '1rem' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'range' }, { key: 'gap', label: 'Gap', type: 'text' }], allowedChildren: ALLOWED_CONTAINER_CHILDREN },
];
