import type { BlockDefinition } from '../types';

export const MARKETING_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// MARKETING
// ═══════════════════════════════════════
  { name: 'Hero Section', type: 'hero', icon: '⚡', category: 'marketing', description: 'Full-width hero with heading + CTA', defaultProps: { title: 'Build Something Amazing', subtitle: 'Create with AI-powered tools.', cta: 'Get Started' }, defaultStyles: { padding: '4rem 2rem', textAlign: 'center', backgroundColor: '#1e1b4b', borderRadius: '0.75rem', marginBottom: '1rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'subtitle', label: 'Subtitle', type: 'text' }, { key: 'cta', label: 'CTA', type: 'text' }] },
  { name: 'Testimonial', type: 'testimonial', icon: '⭐', category: 'marketing', description: 'Customer testimonial card', defaultProps: { quote: 'Best builder we have used.', author: 'Jane Doe', role: 'CEO', avatar: '', rating: 5 }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', marginBottom: '1rem' }, editableProps: [{ key: 'quote', label: 'Quote', type: 'textarea' }, { key: 'author', label: 'Author', type: 'text' }, { key: 'role', label: 'Role', type: 'text' }, { key: 'rating', label: 'Rating', type: 'range' }] },
  { name: 'Pricing Table', type: 'pricing', icon: '💰', category: 'marketing', description: 'Pricing plan card', defaultProps: { plan: 'Pro', price: '$19', interval: '/month', features: ['Feature 1', 'Feature 2', 'Feature 3'], cta: 'Choose Plan', highlighted: false }, defaultStyles: { padding: '2rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', textAlign: 'center' }, editableProps: [{ key: 'plan', label: 'Plan', type: 'text' }, { key: 'price', label: 'Price', type: 'text' }, { key: 'interval', label: 'Interval', type: 'text' }, { key: 'cta', label: 'CTA', type: 'text' }, { key: 'highlighted', label: 'Highlighted', type: 'toggle' }] },
  { name: 'Team Grid', type: 'team-grid', icon: '👥', category: 'marketing', description: 'Team member cards grid', defaultProps: { members: [{ name: 'Alice', role: 'Designer', avatar: '' }, { name: 'Bob', role: 'Developer', avatar: '' }, { name: 'Carol', role: 'PM', avatar: '' }] }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '2rem', padding: '2rem 0' }, editableProps: [] },
  { name: 'Logo Cloud', type: 'logo-cloud', icon: '☁️', category: 'marketing', description: 'Client logo bar', defaultProps: { logos: ['Logo 1', 'Logo 2', 'Logo 3', 'Logo 4', 'Logo 5'] }, defaultStyles: { display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '2rem', padding: '2rem', flexWrap: 'wrap', opacity: '0.6' }, editableProps: [] },
  { name: 'CTA Section', type: 'cta', icon: '📢', category: 'marketing', description: 'Call-to-action banner', defaultProps: { title: 'Ready to Get Started?', subtitle: 'Join thousands of users.', buttonText: 'Sign Up Free', buttonUrl: '#' }, defaultStyles: { padding: '3rem 2rem', textAlign: 'center', backgroundColor: '#7c3aed', borderRadius: '0.75rem', color: '#ffffff', marginBottom: '1rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'subtitle', label: 'Subtitle', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }, { key: 'buttonUrl', label: 'Button URL', type: 'text' }] },
  { name: 'Count Up', type: 'count-up', icon: '📊', category: 'marketing', description: 'Animated number counter', defaultProps: { number: 1000, suffix: '+', label: 'Users', duration: 2 }, defaultStyles: { textAlign: 'center', padding: '1.5rem', fontSize: '2.5rem', fontWeight: '700', color: '#7c3aed' }, editableProps: [{ key: 'number', label: 'Number', type: 'number' }, { key: 'suffix', label: 'Suffix', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }, { key: 'duration', label: 'Duration (s)', type: 'number' }] },
  { name: 'Progress Bar', type: 'progress', icon: '📈', category: 'marketing', description: 'Animated progress bar', defaultProps: { value: 75, max: 100, label: 'Progress', color: '#7c3aed', showLabel: true }, defaultStyles: { width: '100%', marginBottom: '1rem' }, editableProps: [{ key: 'value', label: 'Value', type: 'number' }, { key: 'max', label: 'Max', type: 'number' }, { key: 'label', label: 'Label', type: 'text' }, { key: 'color', label: 'Color', type: 'color' }, { key: 'showLabel', label: 'Show Label', type: 'toggle' }] },
  { name: 'Alert', type: 'alert', icon: '⚠️', category: 'marketing', description: 'Alert / notice banner with dismiss option', defaultProps: { type: 'info', content: 'This is an important notice.', dismissible: true }, defaultStyles: { padding: '1rem', borderRadius: '0.5rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.75rem', fontSize: '0.875rem' }, editableProps: [{ key: 'type', label: 'Type', type: 'select', options: [{ label: 'Info', value: 'info' }, { label: 'Success', value: 'success' }, { label: 'Warning', value: 'warning' }, { label: 'Error', value: 'error' }] }, { key: 'content', label: 'Content', type: 'textarea' }, { key: 'dismissible', label: 'Dismissible', type: 'toggle' }] },
  { name: 'Chart', type: 'chart', icon: '📊', category: 'marketing', description: 'Data chart (bar, line, pie, doughnut, radar)', defaultProps: { type: 'bar', labels: ['Jan', 'Feb', 'Mar', 'Apr'], data: [30, 45, 60, 80], title: 'Chart Title', height: '300px' }, defaultStyles: { width: '100%', height: '300px', padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'type', label: 'Type', type: 'select', options: [{ label: 'Bar', value: 'bar' }, { label: 'Line', value: 'line' }, { label: 'Pie', value: 'pie' }, { label: 'Doughnut', value: 'doughnut' }, { label: 'Radar', value: 'radar' }] }, { key: 'title', label: 'Title', type: 'text' }, { key: 'height', label: 'Height', type: 'text' }] },
  { name: 'AI SEO', type: 'ai-seo', icon: '🔍', category: 'marketing', description: 'AI SEO analysis & suggestions', defaultProps: { content: 'Enter content for SEO analysis.', keywords: ['keyword1', 'keyword2'] }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(236,72,153,0.08)', borderRadius: '0.75rem', border: '1px solid rgba(236,72,153,0.2)' }, editableProps: [{ key: 'content', label: 'Content', type: 'textarea' }] },
  { name: 'AI Recommendation', type: 'ai-recommend', icon: '🎯', category: 'marketing', description: 'Personalized recommendation widget', defaultProps: { category: 'products', count: 4, title: 'Recommended For You', strategy: 'popular' }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(236,72,153,0.08)', borderRadius: '0.75rem', border: '1px solid rgba(236,72,153,0.2)' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'category', label: 'Category', type: 'select', options: [{ label: 'Products', value: 'products' }, { label: 'Posts', value: 'posts' }, { label: 'Pages', value: 'pages' }, { label: 'Custom', value: 'custom' }] }, { key: 'count', label: 'Count', type: 'range' }, { key: 'strategy', label: 'Strategy', type: 'select', options: [{ label: 'Popular', value: 'popular' }, { label: 'Recent', value: 'recent' }, { label: 'Trending', value: 'trending' }, { label: 'Personalized', value: 'personalized' }] }] },
  { name: 'Feature Grid', type: 'feature-grid', icon: '🔲', category: 'marketing', description: 'Grid of feature items with icons', defaultProps: { features: [{ icon: '⚡', title: 'Fast', desc: 'Lightning quick performance.' }, { icon: '🔒', title: 'Secure', desc: 'Enterprise-grade security.' }, { icon: '📱', title: 'Responsive', desc: 'Works on all devices.' }], columns: 3 }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '2rem', padding: '2rem 0', textAlign: 'center' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'range' }] },
  { name: 'Stats Section', type: 'stats-section', icon: '📈', category: 'marketing', description: 'Statistics / numbers display row', defaultProps: { stats: [{ number: '10K+', label: 'Users' }, { number: '99.9%', label: 'Uptime' }, { number: '150+', label: 'Countries' }], layout: 'row' }, defaultStyles: { display: 'flex', justifyContent: 'space-around', padding: '3rem 1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', textAlign: 'center' }, editableProps: [{ key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Row', value: 'row' }, { label: 'Grid', value: 'grid' }] }] },
  { name: 'Newsletter Popup', type: 'newsletter-popup', icon: '📰', category: 'marketing', description: 'Popup newsletter signup form', defaultProps: { title: 'Stay in the Loop', subtitle: 'Get the latest updates.', placeholder: 'your@email.com', buttonText: 'Subscribe', delay: 5, cookieDays: 30 }, defaultStyles: { padding: '2rem', backgroundColor: '#1e293b', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '440px', textAlign: 'center' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'subtitle', label: 'Subtitle', type: 'text' }, { key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'buttonText', label: 'Button Text', type: 'text' }, { key: 'delay', label: 'Delay (s)', type: 'number' }] },
  { name: 'Carousel Testimonials', type: 'carousel-testimonials', icon: '🎠', category: 'marketing', description: 'Rotating testimonials carousel', defaultProps: { items: [{ quote: 'Amazing product!', author: 'Alice', role: 'CEO' }, { quote: 'Transformed our workflow.', author: 'Bob', role: 'Developer' }, { quote: 'Highly recommended.', author: 'Carol', role: 'Designer' }], autoplay: true, interval: 4 }, defaultStyles: { padding: '2rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', textAlign: 'center', maxWidth: '600px', margin: '0 auto' }, editableProps: [{ key: 'autoplay', label: 'Autoplay', type: 'toggle' }, { key: 'interval', label: 'Interval (s)', type: 'number' }] },
];
