import type { BlockDefinition } from '../types';

export const MEDIA_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// MEDIA
// ═══════════════════════════════════════
  { name: 'Image', type: 'image', icon: '🖼️', category: 'media', description: 'Single image with alt + caption', defaultProps: { src: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800', alt: 'Abstract', caption: '' }, defaultStyles: { maxWidth: '100%', borderRadius: '0.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Image URL', type: 'image' }, { key: 'alt', label: 'Alt Text', type: 'text' }, { key: 'caption', label: 'Caption', type: 'text' }] },
  { name: 'Gallery', type: 'gallery', icon: '🖼️', category: 'media', description: 'Image gallery grid or carousel', defaultProps: { images: ['https://picsum.photos/400/300?1', 'https://picsum.photos/400/300?2', 'https://picsum.photos/400/300?3'], columns: 3, mode: 'grid' }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.75rem', marginBottom: '1rem' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'range' }, { key: 'mode', label: 'Mode', type: 'select', options: [{ label: 'Grid', value: 'grid' }, { label: 'Carousel', value: 'carousel' }] }] },
  { name: 'Video', type: 'video', icon: '🎬', category: 'media', description: 'Video embed (YouTube, Vimeo, self-hosted)', defaultProps: { src: 'https://www.youtube.com/embed/dQw4w9WgXcQ', caption: '', autoplay: false, platform: 'youtube' }, defaultStyles: { aspectRatio: '16/9', width: '100%', borderRadius: '0.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Video URL', type: 'video' }, { key: 'caption', label: 'Caption', type: 'text' }, { key: 'platform', label: 'Platform', type: 'select', options: [{ label: 'YouTube', value: 'youtube' }, { label: 'Vimeo', value: 'vimeo' }, { label: 'Self-Hosted', value: 'self' }] }, { key: 'autoplay', label: 'Autoplay', type: 'toggle' }] },
  { name: 'Cover', type: 'cover', icon: '🖼️', category: 'media', description: 'Full-width cover image with overlay', defaultProps: { src: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200', overlay: 'rgba(0,0,0,0.4)', minHeight: '400px', content: 'Cover Content' }, defaultStyles: { backgroundSize: 'cover', backgroundPosition: 'center', minHeight: '400px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '0.5rem', color: '#ffffff', padding: '2rem' }, editableProps: [{ key: 'src', label: 'Background Image', type: 'image' }, { key: 'overlay', label: 'Overlay', type: 'color' }, { key: 'minHeight', label: 'Min Height', type: 'text' }, { key: 'content', label: 'Content', type: 'text' }] },
  { name: 'Media & Text', type: 'media-text', icon: '📰', category: 'media', description: 'Side-by-side media + text', defaultProps: { mediaSrc: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600', content: 'Text content beside media.', mediaPosition: 'left' }, defaultStyles: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', alignItems: 'center', marginBottom: '1rem' }, editableProps: [{ key: 'mediaSrc', label: 'Media URL', type: 'image' }, { key: 'content', label: 'Text', type: 'textarea' }, { key: 'mediaPosition', label: 'Position', type: 'select', options: [{ label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }] },
  { name: 'Audio', type: 'audio', icon: '🎵', category: 'media', description: 'Audio player embed', defaultProps: { src: '', caption: '' }, defaultStyles: { width: '100%', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Audio URL', type: 'text' }, { key: 'caption', label: 'Caption', type: 'text' }] },
  { name: 'File', type: 'file', icon: '📎', category: 'media', description: 'File download block', defaultProps: { href: '#', fileName: 'document.pdf', fileSize: '2.3 MB' }, defaultStyles: { padding: '0.75rem 1rem', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)', marginBottom: '1rem' }, editableProps: [{ key: 'fileName', label: 'File Name', type: 'text' }, { key: 'fileSize', label: 'Size', type: 'text' }] },
  { name: 'Lottie', type: 'lottie', icon: '🎞️', category: 'media', description: 'Lottie animation embed', defaultProps: { src: 'https://assets2.lottiefiles.com/packages/lf20_u4yrau.json', loop: true, speed: 1 }, defaultStyles: { width: '300px', height: '300px', margin: '0 auto', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Lottie JSON URL', type: 'text' }, { key: 'loop', label: 'Loop', type: 'toggle' }, { key: 'speed', label: 'Speed', type: 'number' }] },
  { name: 'SVG', type: 'svg', icon: '🖌️', category: 'media', description: 'Inline SVG or icon set', defaultProps: { svg: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="12" cy="12" r="10"/></svg>', size: '48px' }, defaultStyles: { width: '48px', height: '48px', color: '#7c3aed', marginBottom: '0.5rem' }, editableProps: [{ key: 'svg', label: 'SVG Markup', type: 'textarea' }, { key: 'size', label: 'Size', type: 'text' }] },
  { name: 'Image Hotspot', type: 'image-hotspot', icon: '📍', category: 'media', description: 'Image with clickable hotspots', defaultProps: { src: 'https://picsum.photos/800/500', hotspots: [{ x: 30, y: 40, label: 'Feature A' }, { x: 70, y: 60, label: 'Feature B' }] }, defaultStyles: { position: 'relative', display: 'inline-block', maxWidth: '100%', borderRadius: '0.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Image URL', type: 'image' }] },
  { name: 'Avatar', type: 'avatar', icon: '👤', category: 'media', description: 'User avatar / profile photo', defaultProps: { src: 'https://i.pravatar.cc/150', alt: 'User', size: '64px' }, defaultStyles: { width: '64px', height: '64px', borderRadius: '50%', objectFit: 'cover', marginBottom: '0.5rem' }, editableProps: [{ key: 'src', label: 'Image URL', type: 'image' }, { key: 'alt', label: 'Alt', type: 'text' }, { key: 'size', label: 'Size', type: 'text' }] },
  { name: 'AI Image', type: 'ai-image', icon: '🎨', category: 'media', description: 'Generate image from prompt', defaultProps: { prompt: 'A beautiful landscape with mountains', size: '1024x1024', style: 'natural' }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(59,130,246,0.08)', borderRadius: '0.75rem', border: '1px solid rgba(59,130,246,0.2)' }, editableProps: [{ key: 'prompt', label: 'Prompt', type: 'textarea' }, { key: 'size', label: 'Size', type: 'select', options: [{ label: 'Square (1:1)', value: '1024x1024' }, { label: 'Landscape (16:9)', value: '1792x1024' }, { label: 'Portrait (9:16)', value: '1024x1792' }] }, { key: 'style', label: 'Style', type: 'select', options: [{ label: 'Natural', value: 'natural' }, { label: 'Vivid', value: 'vivid' }, { label: 'Cyberpunk', value: 'cyberpunk' }, { label: 'Watercolor', value: 'watercolor' }, { label: 'Oil Painting', value: 'oil-painting' }] }] },
  { name: 'TTS', type: 'ai-tts', icon: '🔊', category: 'media', description: 'Text-to-speech audio player', defaultProps: { text: 'Text to convert to speech.', voice: 'alloy', speed: 1 }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(34,211,238,0.08)', borderRadius: '0.5rem', border: '1px solid rgba(34,211,238,0.2)', display: 'flex', alignItems: 'center', gap: '1rem' }, editableProps: [{ key: 'text', label: 'Text', type: 'textarea' }, { key: 'voice', label: 'Voice', type: 'select', options: [{ label: 'Alloy', value: 'alloy' }, { label: 'Echo', value: 'echo' }, { label: 'Fable', value: 'fable' }, { label: 'Nova', value: 'nova' }, { label: 'Shimmer', value: 'shimmer' }] }, { key: 'speed', label: 'Speed', type: 'range' }] },
  { name: 'Video Background', type: 'video-bg', icon: '🎥', category: 'media', description: 'Full-width video background', defaultProps: { src: 'https://example.com/video.mp4', poster: '', overlay: 'rgba(0,0,0,0.4)', muted: true, loop: true }, defaultStyles: { position: 'relative', width: '100%', height: '500px', overflow: 'hidden', borderRadius: '0.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Video URL', type: 'text' }, { key: 'poster', label: 'Poster Image', type: 'image' }, { key: 'overlay', label: 'Overlay', type: 'color' }, { key: 'muted', label: 'Muted', type: 'toggle' }, { key: 'loop', label: 'Loop', type: 'toggle' }] },
  { name: 'Image Carousel', type: 'image-carousel', icon: '🎠', category: 'media', description: 'Auto-rotating image carousel', defaultProps: { images: ['https://picsum.photos/800/400?1', 'https://picsum.photos/800/400?2', 'https://picsum.photos/800/400?3'], interval: 5, showArrows: true, showDots: true }, defaultStyles: { position: 'relative', width: '100%', borderRadius: '0.5rem', overflow: 'hidden', marginBottom: '1rem', aspectRatio: '2/1' }, editableProps: [{ key: 'interval', label: 'Interval (s)', type: 'number' }, { key: 'showArrows', label: 'Show Arrows', type: 'toggle' }, { key: 'showDots', label: 'Show Dots', type: 'toggle' }] },
  { name: 'Image Compare', type: 'image-compare', icon: '🔄', category: 'media', description: 'Before/after image slider', defaultProps: { before: 'https://picsum.photos/600/400?before', after: 'https://picsum.photos/600/400?after', labelBefore: 'Before', labelAfter: 'After', initialPosition: 50 }, defaultStyles: { position: 'relative', width: '100%', borderRadius: '0.5rem', overflow: 'hidden', marginBottom: '1rem', cursor: 'ew-resize' }, editableProps: [{ key: 'before', label: 'Before Image', type: 'image' }, { key: 'after', label: 'After Image', type: 'image' }, { key: 'labelBefore', label: 'Before Label', type: 'text' }, { key: 'labelAfter', label: 'After Label', type: 'text' }, { key: 'initialPosition', label: 'Initial Position (%)', type: 'range' }] },
  { name: 'Masonry Gallery', type: 'masonry-gallery', icon: '🖼️', category: 'media', description: 'Variable-height image gallery', defaultProps: { images: ['', '', '', ''], gap: '0.6rem', rounded: true }, defaultStyles: { columnCount: 3, columnGap: '0.6rem', padding: '1rem' }, editableProps: [{ key: 'rounded', label: 'Round Corners', type: 'toggle' }] },
  { name: 'Lightbox Gallery', type: 'lightbox-gallery', icon: '🔎', category: 'media', description: 'Click-to-zoom thumbnail grid', defaultProps: { thumbs: ['', '', '', ''], fullsize: [], columns: 4 }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '0.5rem', padding: '1rem' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'number' }] },
  { name: 'Video Hero', type: 'video-hero', icon: '🎬', category: 'media', description: 'Full-width background video with overlay text', defaultProps: { videoUrl: '', poster: '', headline: '', cta: '', href: '#', overlayOpacity: 45 }, defaultStyles: { minHeight: '420px', display: 'grid', placeItems: 'center', background: '#000', color: '#fff' }, editableProps: [{ key: 'videoUrl', label: 'Video URL', type: 'video' }, { key: 'poster', label: 'Poster', type: 'image' }, { key: 'headline', label: 'Headline', type: 'text' }, { key: 'cta', label: 'CTA Text', type: 'text' }, { key: 'href', label: 'CTA Link', type: 'text' }, { key: 'overlayOpacity', label: 'Overlay %', type: 'range' }] },
  { name: 'Lite YouTube', type: 'youtube-lite', icon: '▶️', category: 'media', description: 'Fast facade embed for YouTube videos', defaultProps: { videoId: 'dQw4w9WgXcQ', title: 'YouTube video' }, defaultStyles: { aspectRatio: '16/9', width: '100%', borderRadius: '0.6rem', overflow: 'hidden' }, editableProps: [{ key: 'videoId', label: 'YouTube Video ID', type: 'text' }] },
  { name: 'Before After', type: 'before-after', icon: '🔀', category: 'media', description: 'Slider comparing two images', defaultProps: { beforeSrc: '', afterSrc: '', beforeLabel: 'Before', afterLabel: 'After', startPercent: 50 }, defaultStyles: { position: 'relative', aspectRatio: '16/9', borderRadius: '0.75rem', overflow: 'hidden' }, editableProps: [{ key: 'beforeSrc', label: 'Before Image', type: 'image' }, { key: 'afterSrc', label: 'After Image', type: 'image' }, { key: 'startPercent', label: 'Start %', type: 'number' }] },
  { name: 'Avatar Stack', type: 'avatar-stack', icon: '👥', category: 'media', description: 'Overlapping team/member avatars', defaultProps: { avatars: [], size: 40, overlap: 12, extraCount: '+24' }, defaultStyles: { display: 'flex', alignItems: 'center', padding: '0.75rem' }, editableProps: [{ key: 'size', label: 'Size (px)', type: 'number' }, { key: 'overlap', label: 'Overlap (px)', type: 'number' }] },
  { name: 'GIF Grid', type: 'gif-grid', icon: '🎞️', category: 'media', description: 'Playful grid of looping GIFs', defaultProps: { gifs: [], columns: 3 }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.5rem', padding: '1rem' }, editableProps: [{ key: 'columns', label: 'Columns', type: 'number' }] },
  { name: 'Screenshot Frame', type: 'screenshot-frame', icon: '🖥', category: 'media', description: 'Browser-chrome mockup around an image', defaultProps: { src: '', url: 'dreammakerhub.website', theme: 'dark' }, defaultStyles: { borderRadius: '0.75rem', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.12)', maxWidth: '720px', margin: '0 auto' }, editableProps: [{ key: 'src', label: 'Screenshot', type: 'image' }, { key: 'url', label: 'Address Bar Text', type: 'text' }] },
  { name: 'Audio Player Card', type: 'audio-player-card', icon: '🎧', category: 'media', description: 'Podcast/track player card', defaultProps: { title: 'Episode 01', artist: 'Wondercast', cover: '', duration: '32:14', src: '' }, defaultStyles: { display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem', borderRadius: '0.75rem', backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '520px' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'artist', label: 'Artist', type: 'text' }, { key: 'cover', label: 'Cover Art', type: 'image' }, { key: 'src', label: 'Audio URL', type: 'text' }] },
];
