import type { BlockDefinition } from '../types';

export const NAVIGATION_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// NAVIGATION
// ═══════════════════════════════════════
  { name: 'WP Menu', type: 'wp-menu', icon: '📋', category: 'navigation', description: 'WP navigation menu', defaultProps: { menuName: 'Primary', orientation: 'horizontal' }, defaultStyles: { display: 'flex', gap: '1.5rem', padding: '0.5rem 0', listStyle: 'none' }, editableProps: [{ key: 'menuName', label: 'Menu Name', type: 'text' }, { key: 'orientation', label: 'Orientation', type: 'select', options: [{ label: 'Horizontal', value: 'horizontal' }, { label: 'Vertical', value: 'vertical' }] }] },
  { name: 'WP Breadcrumbs', type: 'wp-breadcrumbs', icon: '🔗', category: 'navigation', description: 'Breadcrumb navigation', defaultProps: { separator: ' / ', homeText: 'Home' }, defaultStyles: { fontSize: '0.875rem', color: '#94a3b8', padding: '0.5rem 0', marginBottom: '1rem' }, editableProps: [{ key: 'separator', label: 'Separator', type: 'text' }, { key: 'homeText', label: 'Home Text', type: 'text' }] },
  { name: 'Pagination', type: 'pagination', icon: '📄', category: 'navigation', description: 'Page number navigation', defaultProps: { current: 1, total: 10, siblings: 1, showFirstLast: true }, defaultStyles: { display: 'flex', gap: '0.25rem', justifyContent: 'center', padding: '1rem 0', alignItems: 'center' }, editableProps: [{ key: 'current', label: 'Current Page', type: 'number' }, { key: 'total', label: 'Total Pages', type: 'number' }, { key: 'showFirstLast', label: 'Show First/Last', type: 'toggle' }] },
  { name: 'Tags', type: 'tags', icon: '🏷️', category: 'navigation', description: 'Tag / category cloud', defaultProps: { tags: ['AI', 'Design', 'WordPress', 'React', 'Tutorial', 'News'], size: 'md' }, defaultStyles: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem', padding: '0.5rem 0' }, editableProps: [{ key: 'size', label: 'Size', type: 'select', options: [{ label: 'Small', value: 'sm' }, { label: 'Medium', value: 'md' }, { label: 'Large', value: 'lg' }] }] },
  { name: 'Back to Top', type: 'back-to-top', icon: '⬆️', category: 'navigation', description: 'Scroll-to-top button', defaultProps: { offset: 300, label: '', position: 'right' }, defaultStyles: { position: 'fixed', bottom: '2rem', right: '2rem', backgroundColor: '#7c3aed', color: '#ffffff', width: '40px', height: '40px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', boxShadow: '0 4px 12px rgba(124,58,237,0.3)', zIndex: '50' }, editableProps: [{ key: 'offset', label: 'Show After (px)', type: 'number' }, { key: 'position', label: 'Position', type: 'select', options: [{ label: 'Right', value: 'right' }, { label: 'Left', value: 'left' }] }] },
  { name: 'Social Share', type: 'social-share', icon: '🔗', category: 'navigation', description: 'Social share and follow buttons', defaultProps: { platforms: ['twitter', 'facebook', 'linkedin', 'whatsapp'], url: '', title: '', mode: 'share' }, defaultStyles: { display: 'flex', gap: '0.5rem', padding: '0.5rem 0' }, editableProps: [{ key: 'mode', label: 'Mode', type: 'select', options: [{ label: 'Share', value: 'share' }, { label: 'Follow', value: 'follow' }] }] },
  { name: 'Hashtag', type: 'hashtag', icon: '#️⃣', category: 'navigation', description: 'Hashtag link', defaultProps: { tag: 'AI', count: 1234 }, defaultStyles: { color: '#7c3aed', fontWeight: '500', cursor: 'pointer', fontSize: '0.875rem' }, editableProps: [{ key: 'tag', label: 'Hashtag', type: 'text' }] },
  { name: 'Navbar', type: 'navbar', icon: '🧭', category: 'navigation', description: 'Top navigation bar with logo + links', defaultProps: { logo: 'Logo', links: [{ label: 'Home', url: '/' }, { label: 'About', url: '/about' }, { label: 'Contact', url: '/contact' }], sticky: false }, defaultStyles: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 2rem', backgroundColor: 'rgba(15,23,42,0.95)', borderBottom: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'logo', label: 'Logo Text', type: 'text' }, { key: 'sticky', label: 'Sticky', type: 'toggle' }] },
  { name: 'Sidebar Menu', type: 'sidebar-menu', icon: '📋', category: 'navigation', description: 'Vertical sidebar navigation menu', defaultProps: { items: [{ label: 'Dashboard', url: '/dashboard', icon: '📊' }, { label: 'Settings', url: '/settings', icon: '⚙️' }, { label: 'Profile', url: '/profile', icon: '👤' }], collapsible: false }, defaultStyles: { display: 'flex', flexDirection: 'column', gap: '0.25rem', padding: '1rem 0', width: '250px' }, editableProps: [{ key: 'collapsible', label: 'Collapsible', type: 'toggle' }] },
  { name: 'Tab Navigation', type: 'tab-nav', icon: '📑', category: 'navigation', description: 'Tab-based navigation bar', defaultProps: { tabs: [{ label: 'Tab 1', active: true }, { label: 'Tab 2' }, { label: 'Tab 3' }], variant: 'underline' }, defaultStyles: { display: 'flex', gap: '0', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: '1rem' }, editableProps: [{ key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Underline', value: 'underline' }, { label: 'Pills', value: 'pills' }, { label: 'Buttons', value: 'buttons' }] }] },
  { name: 'Dropdown Menu', type: 'dropdown-menu', icon: '▼', category: 'navigation', description: 'Dropdown navigation menu', defaultProps: { label: 'Menu', items: [{ label: 'Item 1', url: '#' }, { label: 'Item 2', url: '#' }, { label: 'Item 3', url: '#' }], align: 'left' }, defaultStyles: { position: 'relative', display: 'inline-block' }, editableProps: [{ key: 'label', label: 'Trigger Label', type: 'text' }, { key: 'align', label: 'Align', type: 'select', options: [{ label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }] },
  { name: 'Table of Contents', type: 'toc', icon: '📑', category: 'navigation', description: 'Auto-generated table of contents', defaultProps: { title: 'Contents', maxLevel: 3, numbered: false }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)', fontSize: '0.875rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'maxLevel', label: 'Max Heading Level', type: 'range' }, { key: 'numbered', label: 'Numbered', type: 'toggle' }] },
];
