import type { BlockDefinition } from '../types';

export const NOTIFICATION_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// NOTIFICATION
// ═══════════════════════════════════════
  { name: 'Toast Notification', type: 'toast', icon: '🔔', category: 'notification', description: 'Temporary toast notification', defaultProps: { message: 'Operation completed!', type: 'success', duration: 3, position: 'bottom-right' }, defaultStyles: { padding: '0.75rem 1.25rem', borderRadius: '0.5rem', fontSize: '0.875rem', fontWeight: '500', display: 'flex', alignItems: 'center', gap: '0.5rem', boxShadow: '0 4px 12px rgba(0,0,0,0.2)' }, editableProps: [{ key: 'message', label: 'Message', type: 'text' }, { key: 'type', label: 'Type', type: 'select', options: [{ label: 'Success', value: 'success' }, { label: 'Error', value: 'error' }, { label: 'Warning', value: 'warning' }, { label: 'Info', value: 'info' }] }, { key: 'duration', label: 'Duration (s)', type: 'number' }, { key: 'position', label: 'Position', type: 'select', options: [{ label: 'Top Right', value: 'top-right' }, { label: 'Top Left', value: 'top-left' }, { label: 'Bottom Right', value: 'bottom-right' }, { label: 'Bottom Left', value: 'bottom-left' }] }] },
  { name: 'Banner Notification', type: 'banner', icon: '📋', category: 'notification', description: 'Top banner notification bar', defaultProps: { message: 'Important announcement here!', type: 'info', dismissible: true, link: '' }, defaultStyles: { padding: '0.75rem 1.5rem', textAlign: 'center', fontSize: '0.875rem', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '1rem' }, editableProps: [{ key: 'message', label: 'Message', type: 'text' }, { key: 'type', label: 'Type', type: 'select', options: [{ label: 'Info', value: 'info' }, { label: 'Success', value: 'success' }, { label: 'Warning', value: 'warning' }, { label: 'Error', value: 'error' }] }, { key: 'dismissible', label: 'Dismissible', type: 'toggle' }, { key: 'link', label: 'Link URL', type: 'text' }] },
  { name: 'Push Notification Prompt', type: 'push-notification', icon: '📲', category: 'notification', description: 'Browser push notification prompt', defaultProps: { title: 'Get Notified', message: 'Allow notifications for updates.', acceptText: 'Allow', declineText: 'Later', icon: '' }, defaultStyles: { padding: '1.25rem', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '360px', textAlign: 'center' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'message', label: 'Message', type: 'text' }, { key: 'acceptText', label: 'Accept Text', type: 'text' }, { key: 'declineText', label: 'Decline Text', type: 'text' }] },
  { name: 'Live Alert', type: 'live-alert', icon: '🚨', category: 'notification', description: 'Real-time live alert bar', defaultProps: { message: 'Live update: Something happened!', severity: 'info', autoHide: true, duration: 5 }, defaultStyles: { padding: '0.75rem 1rem', borderRadius: '0.5rem', fontSize: '0.875rem', display: 'flex', alignItems: 'center', gap: '0.75rem', animation: 'pulse 2s infinite' }, editableProps: [{ key: 'message', label: 'Message', type: 'text' }, { key: 'severity', label: 'Severity', type: 'select', options: [{ label: 'Info', value: 'info' }, { label: 'Warning', value: 'warning' }, { label: 'Critical', value: 'critical' }] }, { key: 'autoHide', label: 'Auto-hide', type: 'toggle' }, { key: 'duration', label: 'Duration (s)', type: 'number' }] },
  { name: 'Announcement Bar', type: 'announcement-bar', icon: '📢', category: 'notification', description: 'Top announcement bar with CTA', defaultProps: { text: 'Free shipping on all orders!', ctaText: 'Shop Now', ctaUrl: '#', bgColor: '#7c3aed', dismissible: true }, defaultStyles: { padding: '0.625rem 1.5rem', textAlign: 'center', fontSize: '0.875rem', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '1rem', fontWeight: '500' }, editableProps: [{ key: 'text', label: 'Announcement', type: 'text' }, { key: 'ctaText', label: 'CTA Text', type: 'text' }, { key: 'ctaUrl', label: 'CTA URL', type: 'text' }, { key: 'bgColor', label: 'Background Color', type: 'color' }, { key: 'dismissible', label: 'Dismissible', type: 'toggle' }] },
];
