import type { BlockDefinition } from '../types';

export const PAYMENT_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// PAYMENT
// ═══════════════════════════════════════
  { name: 'PayPal Button', type: 'paypal', icon: '💳', category: 'payment', description: 'PayPal checkout button', defaultProps: { amount: '29.99', currency: 'USD', env: 'sandbox', clientId: '', label: 'checkout' }, defaultStyles: { display: 'flex', justifyContent: 'center', padding: '0.5rem 0' }, editableProps: [{ key: 'amount', label: 'Amount', type: 'text' }, { key: 'currency', label: 'Currency', type: 'text' }, { key: 'env', label: 'Environment', type: 'select', options: [{ label: 'Sandbox', value: 'sandbox' }, { label: 'Production', value: 'production' }] }, { key: 'clientId', label: 'Client ID', type: 'text' }, { key: 'label', label: 'Button Label', type: 'select', options: [{ label: 'Checkout', value: 'checkout' }, { label: 'Pay', value: 'pay' }, { label: 'Buy Now', value: 'buynow' }] }] },
  { name: 'Stripe Payment', type: 'stripe', icon: '💳', category: 'payment', description: 'Stripe card element', defaultProps: { amount: '29.99', currency: 'usd', publishableKey: '', description: 'Payment for order', mode: 'payment' }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '500px' }, editableProps: [{ key: 'amount', label: 'Amount', type: 'text' }, { key: 'currency', label: 'Currency', type: 'text' }, { key: 'publishableKey', label: 'Publishable Key', type: 'text' }, { key: 'description', label: 'Description', type: 'text' }, { key: 'mode', label: 'Mode', type: 'select', options: [{ label: 'Payment', value: 'payment' }, { label: 'Subscription', value: 'subscription' }] }] },
  { name: 'Apple Pay', type: 'apple-pay', icon: '🍎', category: 'payment', description: 'Apple Pay button', defaultProps: { amount: '29.99', currency: 'USD', merchantId: '', label: 'Store Purchase' }, defaultStyles: { display: 'flex', justifyContent: 'center', padding: '0.5rem 0' }, editableProps: [{ key: 'amount', label: 'Amount', type: 'text' }, { key: 'currency', label: 'Currency', type: 'text' }, { key: 'merchantId', label: 'Merchant ID', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }] },
  { name: 'Google Pay', type: 'google-pay', icon: '💳', category: 'payment', description: 'Google Pay button', defaultProps: { amount: '29.99', currency: 'USD', merchantId: '', gateway: '' }, defaultStyles: { display: 'flex', justifyContent: 'center', padding: '0.5rem 0' }, editableProps: [{ key: 'amount', label: 'Amount', type: 'text' }, { key: 'currency', label: 'Currency', type: 'text' }, { key: 'merchantId', label: 'Merchant ID', type: 'text' }, { key: 'gateway', label: 'Gateway', type: 'text' }] },
  { name: 'Payment Icons', type: 'payment-icons', icon: '🏦', category: 'payment', description: 'Accepted payment methods display', defaultProps: { methods: ['visa', 'mastercard', 'amex', 'paypal', 'applepay', 'googlepay'], size: 'md', showLabels: false }, defaultStyles: { display: 'flex', gap: '0.75rem', justifyContent: 'center', alignItems: 'center', padding: '1rem 0', flexWrap: 'wrap' }, editableProps: [{ key: 'size', label: 'Icon Size', type: 'select', options: [{ label: 'Small', value: 'sm' }, { label: 'Medium', value: 'md' }, { label: 'Large', value: 'lg' }] }, { key: 'showLabels', label: 'Show Labels', type: 'toggle' }] },
];
