import type { BlockDefinition } from '../types';

export const PRODUCTS_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// PRODUCTS
// ═══════════════════════════════════════
  { name: 'Product Page', type: 'product-page', icon: '📄', category: 'products', description: 'Full product page layout', defaultProps: { name: 'Product Name', price: '$49.99', images: ['https://picsum.photos/600/600?1', 'https://picsum.photos/600/600?2'], description: 'Product description here.' }, defaultStyles: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '3rem', padding: '2rem', maxWidth: '1200px', margin: '0 auto' }, editableProps: [{ key: 'name', label: 'Product Name', type: 'text' }, { key: 'price', label: 'Price', type: 'text' }, { key: 'description', label: 'Description', type: 'textarea' }] },
  { name: 'Product Filter', type: 'product-filter', icon: '🔍', category: 'products', description: 'Product filter and sort bar', defaultProps: { sortOptions: ['Newest', 'Price Low', 'Price High', 'Popular'], showFilter: true, layout: 'grid' }, defaultStyles: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 0', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '0.5rem' }, editableProps: [{ key: 'showFilter', label: 'Show Filter', type: 'toggle' }, { key: 'layout', label: 'Default Layout', type: 'select', options: [{ label: 'Grid', value: 'grid' }, { label: 'List', value: 'list' }] }] },
  { name: 'Product Search', type: 'product-search', icon: '🔎', category: 'products', description: 'Product search with autocomplete', defaultProps: { placeholder: 'Search products...', showSuggestions: true, maxSuggestions: 5 }, defaultStyles: { position: 'relative', width: '100%', maxWidth: '400px' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'showSuggestions', label: 'Show Suggestions', type: 'toggle' }, { key: 'maxSuggestions', label: 'Max Suggestions', type: 'number' }] },
  { name: 'Product Tabs', type: 'product-tabs', icon: '📑', category: 'products', description: 'Product details tabs (description, reviews, shipping)', defaultProps: { tabs: [{ label: 'Description', content: 'Product description here.' }, { label: 'Reviews', content: 'Customer reviews here.' }, { label: 'Shipping', content: 'Shipping info here.' }] }, defaultStyles: { marginTop: '2rem', padding: '1rem 0', borderTop: '1px solid rgba(255,255,255,0.1)' }, editableProps: [] },
  { name: 'Related Products', type: 'related-products', icon: '🔗', category: 'products', description: 'Related products carousel', defaultProps: { title: 'You May Also Like', count: 4, columns: 4 }, defaultStyles: { padding: '2rem 0', borderTop: '1px solid rgba(255,255,255,0.1)', marginTop: '2rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'count', label: 'Count', type: 'number' }, { key: 'columns', label: 'Columns', type: 'range' }] },
  { name: 'Product Badge', type: 'product-badge', icon: '🏷️', category: 'products', description: 'Sale/new/featured product badge', defaultProps: { text: 'Sale!', variant: 'sale', position: 'top-right' }, defaultStyles: { position: 'absolute', top: '0.75rem', right: '0.75rem', padding: '0.25rem 0.75rem', borderRadius: '9999px', fontSize: '0.75rem', fontWeight: '700', zIndex: '10' }, editableProps: [{ key: 'text', label: 'Badge Text', type: 'text' }, { key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Sale', value: 'sale' }, { label: 'New', value: 'new' }, { label: 'Featured', value: 'featured' }, { label: 'Best Seller', value: 'bestseller' }] }, { key: 'position', label: 'Position', type: 'select', options: [{ label: 'Top Right', value: 'top-right' }, { label: 'Top Left', value: 'top-left' }] }] },
  { name: 'Stock Indicator', type: 'stock-indicator', icon: '📦', category: 'products', description: 'In stock / out of stock indicator', defaultProps: { status: 'in-stock', quantity: 25, lowStockThreshold: 5 }, defaultStyles: { display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem', marginBottom: '0.75rem' }, editableProps: [{ key: 'status', label: 'Status', type: 'select', options: [{ label: 'In Stock', value: 'in-stock' }, { label: 'Out of Stock', value: 'out-of-stock' }, { label: 'Pre-order', value: 'pre-order' }] }, { key: 'quantity', label: 'Quantity', type: 'number' }, { key: 'lowStockThreshold', label: 'Low Stock Threshold', type: 'number' }] },
  { name: 'Product Video', type: 'product-video', icon: '🎥', category: 'products', description: 'Product video embed', defaultProps: { src: '', title: 'Product Video', autoplay: false }, defaultStyles: { width: '100%', aspectRatio: '16/9', borderRadius: '0.5rem', overflow: 'hidden', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Video URL', type: 'text' }, { key: 'title', label: 'Title', type: 'text' }, { key: 'autoplay', label: 'Autoplay', type: 'toggle' }] },
  { name: 'Size Chart', type: 'size-chart', icon: '📏', category: 'products', description: 'Size guide / measurement chart', defaultProps: { sizes: [{ size: 'S', chest: '36"', waist: '30"' }, { size: 'M', chest: '38"', waist: '32"' }, { size: 'L', chest: '40"', waist: '34"' }], title: 'Size Guide' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)', marginBottom: '1rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }] },
  { name: 'Bundle Offer', type: 'bundle-offer', icon: '🎁', category: 'products', description: 'Product bundle deal display', defaultProps: { bundleName: 'Starter Pack', items: ['Product A', 'Product B', 'Product C'], price: '$79.99', originalPrice: '$99.99', cta: 'Buy Bundle' }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(245,158,11,0.06)', borderRadius: '0.75rem', border: '2px solid rgba(245,158,11,0.3)', textAlign: 'center' }, editableProps: [{ key: 'bundleName', label: 'Bundle Name', type: 'text' }, { key: 'price', label: 'Price', type: 'text' }, { key: 'originalPrice', label: 'Original Price', type: 'text' }, { key: 'cta', label: 'CTA', type: 'text' }] },
];
