import type { BlockDefinition } from '../types';

export const PRODUCTS_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// PRODUCTS
// ═══════════════════════════════════════
  { name: 'Product Page', type: 'product-page', icon: '📄', category: 'products', description: 'Full product page layout', defaultProps: { name: 'Product Name', price: '$49.99', images: ['https://picsum.photos/600/600?1', 'https://picsum.photos/600/600?2'], description: 'Product description here.' }, defaultStyles: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '3rem', padding: '2rem', maxWidth: '1200px', margin: '0 auto' }, editableProps: [{ key: 'name', label: 'Product Name', type: 'text' }, { key: 'price', label: 'Price', type: 'text' }, { key: 'description', label: 'Description', type: 'textarea' }] },
  { name: 'Product Filter', type: 'product-filter', icon: '🔍', category: 'products', description: 'Product filter and sort bar', defaultProps: { sortOptions: ['Newest', 'Price Low', 'Price High', 'Popular'], showFilter: true, layout: 'grid' }, defaultStyles: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 0', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '0.5rem' }, editableProps: [{ key: 'showFilter', label: 'Show Filter', type: 'toggle' }, { key: 'layout', label: 'Default Layout', type: 'select', options: [{ label: 'Grid', value: 'grid' }, { label: 'List', value: 'list' }] }] },
  { name: 'Product Search', type: 'product-search', icon: '🔎', category: 'products', description: 'Product search with autocomplete', defaultProps: { placeholder: 'Search products...', showSuggestions: true, maxSuggestions: 5 }, defaultStyles: { position: 'relative', width: '100%', maxWidth: '400px' }, editableProps: [{ key: 'placeholder', label: 'Placeholder', type: 'text' }, { key: 'showSuggestions', label: 'Show Suggestions', type: 'toggle' }, { key: 'maxSuggestions', label: 'Max Suggestions', type: 'number' }] },
  { name: 'Product Tabs', type: 'product-tabs', icon: '📑', category: 'products', description: 'Product details tabs (description, reviews, shipping)', defaultProps: { tabs: [{ label: 'Description', content: 'Product description here.' }, { label: 'Reviews', content: 'Customer reviews here.' }, { label: 'Shipping', content: 'Shipping info here.' }] }, defaultStyles: { marginTop: '2rem', padding: '1rem 0', borderTop: '1px solid rgba(255,255,255,0.1)' }, editableProps: [] },
  { name: 'Related Products', type: 'related-products', icon: '🔗', category: 'products', description: 'Related products carousel', defaultProps: { title: 'You May Also Like', count: 4, columns: 4 }, defaultStyles: { padding: '2rem 0', borderTop: '1px solid rgba(255,255,255,0.1)', marginTop: '2rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'count', label: 'Count', type: 'number' }, { key: 'columns', label: 'Columns', type: 'range' }] },
  { name: 'Product Badge', type: 'product-badge', icon: '🏷️', category: 'products', description: 'Sale/new/featured product badge', defaultProps: { text: 'Sale!', variant: 'sale', position: 'top-right' }, defaultStyles: { position: 'absolute', top: '0.75rem', right: '0.75rem', padding: '0.25rem 0.75rem', borderRadius: '9999px', fontSize: '0.75rem', fontWeight: '700', zIndex: '10' }, editableProps: [{ key: 'text', label: 'Badge Text', type: 'text' }, { key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Sale', value: 'sale' }, { label: 'New', value: 'new' }, { label: 'Featured', value: 'featured' }, { label: 'Best Seller', value: 'bestseller' }] }, { key: 'position', label: 'Position', type: 'select', options: [{ label: 'Top Right', value: 'top-right' }, { label: 'Top Left', value: 'top-left' }] }] },
  { name: 'Stock Indicator', type: 'stock-indicator', icon: '📦', category: 'products', description: 'In stock / out of stock indicator', defaultProps: { status: 'in-stock', quantity: 25, lowStockThreshold: 5 }, defaultStyles: { display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem', marginBottom: '0.75rem' }, editableProps: [{ key: 'status', label: 'Status', type: 'select', options: [{ label: 'In Stock', value: 'in-stock' }, { label: 'Out of Stock', value: 'out-of-stock' }, { label: 'Pre-order', value: 'pre-order' }] }, { key: 'quantity', label: 'Quantity', type: 'number' }, { key: 'lowStockThreshold', label: 'Low Stock Threshold', type: 'number' }] },
  { name: 'Product Video', type: 'product-video', icon: '🎥', category: 'products', description: 'Product video embed', defaultProps: { src: '', title: 'Product Video', autoplay: false }, defaultStyles: { width: '100%', aspectRatio: '16/9', borderRadius: '0.5rem', overflow: 'hidden', marginBottom: '1rem' }, editableProps: [{ key: 'src', label: 'Video URL', type: 'text' }, { key: 'title', label: 'Title', type: 'text' }, { key: 'autoplay', label: 'Autoplay', type: 'toggle' }] },
  { name: 'Size Chart', type: 'size-chart', icon: '📏', category: 'products', description: 'Size guide / measurement chart', defaultProps: { sizes: [{ size: 'S', chest: '36"', waist: '30"' }, { size: 'M', chest: '38"', waist: '32"' }, { size: 'L', chest: '40"', waist: '34"' }], title: 'Size Guide' }, defaultStyles: { padding: '1rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.5rem', border: '1px solid rgba(255,255,255,0.1)', marginBottom: '1rem' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }] },
  { name: 'Bundle Offer', type: 'bundle-offer', icon: '🎁', category: 'products', description: 'Product bundle deal display', defaultProps: { bundleName: 'Starter Pack', items: ['Product A', 'Product B', 'Product C'], price: '$79.99', originalPrice: '$99.99', cta: 'Buy Bundle' }, defaultStyles: { padding: '1.5rem', backgroundColor: 'rgba(245,158,11,0.06)', borderRadius: '0.75rem', border: '2px solid rgba(245,158,11,0.3)', textAlign: 'center' }, editableProps: [{ key: 'bundleName', label: 'Bundle Name', type: 'text' }, { key: 'price', label: 'Price', type: 'text' }, { key: 'originalPrice', label: 'Original Price', type: 'text' }, { key: 'cta', label: 'CTA', type: 'text' }] },
  { name: 'Product Grid 3', type: 'product-grid-3', icon: '🧺', category: 'products', description: 'Three-column product catalog grid', defaultProps: { heading: 'Best sellers', products: [{ name: 'Studio Tee', price: '$28', image: '', badge: '' }, { name: 'Wonder Mug', price: '$18', image: '', badge: 'New' }, { name: 'Dev Hoodie', price: '$64', image: '', badge: '' }], showBadge: true }, defaultStyles: { padding: '2rem', maxWidth: '1080px', margin: '0 auto' }, editableProps: [{ key: 'heading', label: 'Heading', type: 'text' }, { key: 'showBadge', label: 'Show Badges', type: 'toggle' }] },

  { name: 'Collection Banner', type: 'collection-banner', icon: '🏞️', category: 'products', description: 'Category hero with shop link', defaultProps: { title: 'Autumn Collection', subtitle: '72 new pieces', cta: 'Shop the drop', href: '#', image: '', align: 'left' }, defaultStyles: { minHeight: 260, display: 'flex', flexDirection: 'column', justifyContent: 'center', padding: '2.5rem', borderRadius: '1rem', color: '#fff', backgroundSize: 'cover', backgroundPosition: 'center' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'subtitle', label: 'Subtitle', type: 'text' }, { key: 'cta', label: 'Button Text', type: 'text' }, { key: 'href', label: 'Link', type: 'text' }, { key: 'image', label: 'Background Image', type: 'image' }] },

  { name: 'Variant Picker', type: 'variant-picker', icon: '🎨', category: 'products', description: 'Size/color/variant selector row', defaultProps: { label: 'Size', options: ['XS', 'S', 'M', 'L', 'XL'], active: 2, swatches: [] }, defaultStyles: { display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.5rem', padding: '0.75rem 0' }, editableProps: [{ key: 'label', label: 'Label', type: 'text' }, { key: 'active', label: 'Selected Index', type: 'number' }] },

  { name: 'Stock Badge', type: 'stock-badge', icon: '📦', category: 'products', description: 'Low-stock urgency indicator', defaultProps: { stock: 4, lowThreshold: 5, inStockText: 'In stock', lowText: 'Only {n} left!', outText: 'Sold out' }, defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.78rem', fontWeight: 700, padding: '0.25rem 0.7rem', borderRadius: 999, width: 'fit-content' }, editableProps: [{ key: 'stock', label: 'Stock Qty', type: 'number' }, { key: 'lowThreshold', label: 'Low Threshold', type: 'number' }] },

  { name: 'Bundle Builder', type: 'bundle-builder', icon: '🎁', category: 'products', description: 'Pick-N bundle with progress discount', defaultProps: { pickLabel: 'Pick any 3 for 20% off', picksNeeded: 3, discountPct: 20, items: ['Cleanser', 'Serum', 'SPF', 'Moisturizer'] }, defaultStyles: { padding: '1.5rem', borderRadius: '0.9rem', border: '1px dashed rgba(255,255,255,0.2)', maxWidth: '640px', margin: '0 auto' }, editableProps: [{ key: 'pickLabel', label: 'Offer Text', type: 'text' }, { key: 'picksNeeded', label: 'Picks Needed', type: 'number' }, { key: 'discountPct', label: 'Discount %', type: 'number' }] },

  { name: 'Subscription Product', type: 'subscription-product', icon: '🔁', category: 'products', description: 'Recurring purchase option cards', defaultProps: { plans: [{ label: 'Monthly', price: '$19' }, { label: 'Yearly', price: '$190', note: 'Save $38' }], active: 1 }, defaultStyles: { display: 'grid', gap: '0.75rem', maxWidth: '480px', margin: '0 auto', padding: '1rem' }, editableProps: [{ key: 'active', label: 'Selected Plan', type: 'number' }] },

  { name: 'Gift Card', type: 'gift-card', icon: '💳', category: 'products', description: 'Digital gift card presenter', defaultProps: { amounts: [25, 50, 100], currency: '$', note: 'Delivered by email instantly', cta: 'Buy gift card' }, defaultStyles: { textAlign: 'center', padding: '1.5rem', borderRadius: '1rem', background: 'linear-gradient(135deg, rgba(236,72,153,0.12), rgba(168,85,247,0.12))', border: '1px solid rgba(236,72,153,0.3)', maxWidth: '520px', margin: '0 auto' }, editableProps: [{ key: 'currency', label: 'Currency Symbol', type: 'text' }, { key: 'note', label: 'Note', type: 'text' }, { key: 'cta', label: 'Button Text', type: 'text' }] },

  { name: 'Recently Viewed', type: 'recently-viewed', icon: '🕘', category: 'products', description: 'Horizontal rail of last-viewed items', defaultProps: { heading: 'Recently viewed', count: 4 }, defaultStyles: { padding: '1rem 0', overflowX: 'auto' }, editableProps: [{ key: 'heading', label: 'Heading', type: 'text' }, { key: 'count', label: 'Item Count', type: 'number' }] },

];
