import type { BlockDefinition } from '../types';

export const SOCIAL_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// SOCIAL
// ═══════════════════════════════════════
  { name: 'WhatsApp Share', type: 'whatsapp-share', icon: '📱', category: 'social', description: 'WhatsApp share button', defaultProps: { text: 'Check this out!', url: '', showCount: false }, defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem', backgroundColor: '#25D366', color: '#ffffff', borderRadius: '0.5rem', cursor: 'pointer', fontSize: '0.875rem', fontWeight: '600', border: 'none' }, editableProps: [{ key: 'text', label: 'Share Text', type: 'text' }, { key: 'url', label: 'URL', type: 'text' }, { key: 'showCount', label: 'Show Count', type: 'toggle' }] },
  { name: 'Telegram Share', type: 'telegram-share', icon: '✈️', category: 'social', description: 'Telegram share button', defaultProps: { text: 'Check this out!', url: '' }, defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem', backgroundColor: '#0088cc', color: '#ffffff', borderRadius: '0.5rem', cursor: 'pointer', fontSize: '0.875rem', fontWeight: '600', border: 'none' }, editableProps: [{ key: 'text', label: 'Share Text', type: 'text' }, { key: 'url', label: 'URL', type: 'text' }] },
  { name: 'Pinterest Pin', type: 'pinterest-pin', icon: '📌', category: 'social', description: 'Pinterest save/pin button', defaultProps: { url: '', image: '', description: '' }, defaultStyles: { display: 'inline-block', cursor: 'pointer' }, editableProps: [{ key: 'url', label: 'Pin URL', type: 'text' }, { key: 'image', label: 'Image URL', type: 'image' }, { key: 'description', label: 'Description', type: 'text' }] },
  { name: 'YouTube Subscribe', type: 'youtube-sub', icon: '▶️', category: 'social', description: 'YouTube subscribe button', defaultProps: { channelId: '', channelName: 'My Channel', layout: 'default', count: 'default' }, defaultStyles: { display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.5rem 0' }, editableProps: [{ key: 'channelId', label: 'Channel ID', type: 'text' }, { key: 'channelName', label: 'Channel Name', type: 'text' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Default', value: 'default' }, { label: 'Full', value: 'full' }] }] },
  { name: 'Discord Invite', type: 'discord-invite', icon: '💬', category: 'social', description: 'Discord server invite widget', defaultProps: { inviteCode: '', serverName: 'My Server', memberCount: 0, onlineCount: 0 }, defaultStyles: { padding: '1.25rem', backgroundColor: '#5865F215', borderRadius: '0.75rem', border: '1px solid #5865F230', display: 'flex', alignItems: 'center', gap: '1rem', maxWidth: '400px' }, editableProps: [{ key: 'inviteCode', label: 'Invite Code', type: 'text' }, { key: 'serverName', label: 'Server Name', type: 'text' }] },
  { name: 'GitHub Star', type: 'github-star', icon: '⭐', category: 'social', description: 'GitHub star / repo badge', defaultProps: { repo: 'user/repo', showCount: true, size: 'large' }, defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }, editableProps: [{ key: 'repo', label: 'Repository', type: 'text' }, { key: 'showCount', label: 'Show Stars', type: 'toggle' }, { key: 'size', label: 'Size', type: 'select', options: [{ label: 'Small', value: 'small' }, { label: 'Large', value: 'large' }] }] },
  { name: 'LinkedIn Follow', type: 'linkedin-follow', icon: '💼', category: 'social', description: 'LinkedIn follow/connect button', defaultProps: { companyId: '', label: 'Follow', showCount: false }, defaultStyles: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.5rem 1rem', backgroundColor: '#0A66C2', color: '#ffffff', borderRadius: '0.25rem', cursor: 'pointer', fontSize: '0.875rem', fontWeight: '600', border: 'none' }, editableProps: [{ key: 'companyId', label: 'Company ID', type: 'text' }, { key: 'label', label: 'Button Text', type: 'text' }, { key: 'showCount', label: 'Show Count', type: 'toggle' }] },
  { name: 'Social Feed', type: 'social-feed', icon: '📰', category: 'social', description: 'Aggregated social media feed', defaultProps: { sources: ['twitter', 'instagram'], count: 6, layout: 'grid', columns: 3 }, defaultStyles: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', padding: '1rem 0' }, editableProps: [{ key: 'count', label: 'Count', type: 'number' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'Grid', value: 'grid' }, { label: 'List', value: 'list' }] }, { key: 'columns', label: 'Columns', type: 'range' }] },
  { name: 'Facebook Page', type: 'facebook-page', icon: '📘', category: 'social', description: 'Facebook page embed plugin', defaultProps: { pageUrl: 'https://facebook.com/example', tabs: 'timeline', width: 340, height: 500, hideCover: false }, defaultStyles: { marginBottom: '1rem', overflow: 'hidden', borderRadius: '0.5rem' }, editableProps: [{ key: 'pageUrl', label: 'Page URL', type: 'text' }, { key: 'tabs', label: 'Tabs', type: 'select', options: [{ label: 'Timeline', value: 'timeline' }, { label: 'Events', value: 'events' }, { label: 'Messages', value: 'messages' }] }, { key: 'hideCover', label: 'Hide Cover', type: 'toggle' }] },
  { name: 'Twitter Timeline', type: 'twitter-timeline', icon: '🐦', category: 'social', description: 'Twitter/X profile timeline embed', defaultProps: { username: 'username', height: 500, theme: 'dark', showReplies: false }, defaultStyles: { marginBottom: '1rem', borderRadius: '0.5rem', overflow: 'hidden' }, editableProps: [{ key: 'username', label: 'Username', type: 'text' }, { key: 'height', label: 'Height', type: 'number' }, { key: 'theme', label: 'Theme', type: 'select', options: [{ label: 'Dark', value: 'dark' }, { label: 'Light', value: 'light' }] }, { key: 'showReplies', label: 'Show Replies', type: 'toggle' }] },
];
