import type { BlockDefinition } from '../types';

export const TYPOGRAPHY_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// TYPOGRAPHY
// ═══════════════════════════════════════
  { name: 'Heading', type: 'heading', icon: '🔤', category: 'typography', description: 'H1–H6 heading with configurable level', defaultProps: { level: 'h2', content: 'New Heading' }, defaultStyles: { fontSize: '1.875rem', fontWeight: '700', color: '#ffffff', lineHeight: '1.2', marginBottom: '0.5rem' }, editableProps: [{ key: 'content', label: 'Text', type: 'text' }, { key: 'level', label: 'Level', type: 'select', options: [{ label: 'H1', value: 'h1' }, { label: 'H2', value: 'h2' }, { label: 'H3', value: 'h3' }, { label: 'H4', value: 'h4' }, { label: 'H5', value: 'h5' }, { label: 'H6', value: 'h6' }] }] },
  { name: 'Paragraph', type: 'paragraph', icon: '📝', category: 'typography', description: 'Body text with size and drop cap options', defaultProps: { content: 'This is a paragraph of text.', size: 'normal', dropCap: false }, defaultStyles: { fontSize: '1rem', color: '#cbd5e1', lineHeight: '1.75', marginBottom: '1rem' }, editableProps: [{ key: 'content', label: 'Text', type: 'textarea' }, { key: 'size', label: 'Size', type: 'select', options: [{ label: 'Small', value: 'small' }, { label: 'Normal', value: 'normal' }, { label: 'Large', value: 'large' }] }, { key: 'dropCap', label: 'Drop Cap', type: 'toggle' }] },
  { name: 'Rich Text', type: 'rich-text', icon: '📄', category: 'typography', description: 'Multi-line rich content with HTML', defaultProps: { content: '<p>Rich content area.</p>' }, defaultStyles: { padding: '1rem', color: '#cbd5e1', lineHeight: '1.75' }, editableProps: [{ key: 'content', label: 'HTML', type: 'textarea' }] },
  { name: 'List', type: 'list', icon: '📋', category: 'typography', description: 'Bulleted or numbered list', defaultProps: { items: ['Item one', 'Item two', 'Item three'], listType: 'unordered' }, defaultStyles: { paddingLeft: '1.5rem', color: '#cbd5e1', lineHeight: '1.75' }, editableProps: [{ key: 'listType', label: 'Type', type: 'select', options: [{ label: 'Bulleted', value: 'unordered' }, { label: 'Numbered', value: 'ordered' }] }] },
  { name: 'Quote', type: 'quote', icon: '💬', category: 'typography', description: 'Blockquote with citation and variant', defaultProps: { content: 'The future belongs to those who believe.', citation: 'Eleanor Roosevelt', variant: 'standard' }, defaultStyles: { borderLeft: '4px solid #7c3aed', padding: '1rem 1.5rem', fontStyle: 'italic', color: '#e2e8f0', backgroundColor: 'rgba(124,58,237,0.08)', borderRadius: '0.5rem' }, editableProps: [{ key: 'content', label: 'Quote', type: 'textarea' }, { key: 'citation', label: 'Citation', type: 'text' }, { key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Standard', value: 'standard' }, { label: 'Pull Quote', value: 'pullquote' }] }] },
  { name: 'Code', type: 'code', icon: '💻', category: 'typography', description: 'Code block with syntax highlighting', defaultProps: { content: 'const x = 42;', language: 'javascript' }, defaultStyles: { fontFamily: '"Fira Code", monospace', fontSize: '0.875rem', backgroundColor: '#1e293b', padding: '1rem', borderRadius: '0.5rem', color: '#a5f3fc', overflow: 'auto' }, editableProps: [{ key: 'content', label: 'Code', type: 'textarea' }, { key: 'language', label: 'Language', type: 'select', options: [{ label: 'JavaScript', value: 'javascript' }, { label: 'TypeScript', value: 'typescript' }, { label: 'Python', value: 'python' }, { label: 'HTML', value: 'html' }, { label: 'CSS', value: 'css' }, { label: 'SQL', value: 'sql' }, { label: 'Bash', value: 'bash' }, { label: 'JSON', value: 'json' }] }] },
  { name: 'Verse', type: 'verse', icon: '✍️', category: 'typography', description: 'Poetry / verse formatting', defaultProps: { content: 'Roses are red\nViolets are blue\nThis block\nIs just for you.' }, defaultStyles: { fontFamily: 'Georgia, serif', fontSize: '1.125rem', fontStyle: 'italic', lineHeight: '2', color: '#e2e8f0', padding: '1rem', textAlign: 'center' }, editableProps: [{ key: 'content', label: 'Verse', type: 'textarea' }] },
  { name: 'Typewriter', type: 'typewriter', icon: '⌨️', category: 'typography', description: 'Typewriter animated text', defaultProps: { words: ['Create', 'Build', 'Launch'], speed: 100, loop: true }, defaultStyles: { fontSize: '1.5rem', fontWeight: '700', color: '#7c3aed', fontFamily: 'monospace' }, editableProps: [{ key: 'speed', label: 'Speed (ms)', type: 'number' }, { key: 'loop', label: 'Loop', type: 'toggle' }] },
  { name: 'Badge', type: 'badge', icon: '🏷️', category: 'typography', description: 'Small label / tag badge', defaultProps: { content: 'New', variant: 'primary' }, defaultStyles: { display: 'inline-block', padding: '0.25rem 0.625rem', fontSize: '0.75rem', fontWeight: '600', borderRadius: '9999px', backgroundColor: '#7c3aed', color: '#ffffff' }, editableProps: [{ key: 'content', label: 'Text', type: 'text' }, { key: 'variant', label: 'Variant', type: 'select', options: [{ label: 'Primary', value: 'primary' }, { label: 'Success', value: 'success' }, { label: 'Warning', value: 'warning' }, { label: 'Danger', value: 'danger' }] }] },
  { name: 'Icon List', type: 'icon-list', icon: '✅', category: 'typography', description: 'List with custom icons', defaultProps: { items: [{ icon: '✅', text: 'Feature one' }, { icon: '✅', text: 'Feature two' }, { icon: '✅', text: 'Feature three' }] }, defaultStyles: { display: 'flex', flexDirection: 'column', gap: '0.75rem', padding: '0.5rem 0' }, editableProps: [] },
  { name: 'Animated Text', type: 'animated-text', icon: '🎭', category: 'typography', description: 'Text with entrance animation', defaultProps: { content: 'Animate Me', animation: 'fadeIn', delay: 0 }, defaultStyles: { fontSize: '1.5rem', fontWeight: '700', color: '#ffffff' }, editableProps: [{ key: 'content', label: 'Text', type: 'text' }, { key: 'animation', label: 'Animation', type: 'select', options: [{ label: 'Fade In', value: 'fadeIn' }, { label: 'Slide Up', value: 'slideUp' }, { label: 'Slide In', value: 'slideIn' }, { label: 'Zoom', value: 'zoom' }, { label: 'Bounce', value: 'bounce' }] }, { key: 'delay', label: 'Delay (ms)', type: 'number' }] },
  { name: 'Icon', type: 'icon', icon: '✨', category: 'typography', description: 'Decorative icon / emoji', defaultProps: { icon: '✨', size: '2rem' }, defaultStyles: { fontSize: '2rem', textAlign: 'center', marginBottom: '0.5rem' }, editableProps: [{ key: 'icon', label: 'Icon', type: 'text' }, { key: 'size', label: 'Size', type: 'text' }] },
  { name: 'Highlight Text', type: 'highlight-text', icon: '🖍️', category: 'typography', description: 'Text with background highlight', defaultProps: { content: 'Highlighted text', color: '#fef08a', style: 'marker' }, defaultStyles: { display: 'inline', padding: '0.125rem 0.25rem', borderRadius: '0.25rem', fontWeight: '500' }, editableProps: [{ key: 'content', label: 'Text', type: 'text' }, { key: 'color', label: 'Color', type: 'color' }, { key: 'style', label: 'Style', type: 'select', options: [{ label: 'Marker', value: 'marker' }, { label: 'Underline', value: 'underline' }, { label: 'Strikethrough', value: 'strikethrough' }] }] },
  { name: 'Tooltip', type: 'tooltip', icon: '💡', category: 'typography', description: 'Hover tooltip text', defaultProps: { text: 'Hover over me', tooltip: 'Extra info here', position: 'top' }, defaultStyles: { position: 'relative', display: 'inline-block', cursor: 'pointer', borderBottom: '1px dashed rgba(255,255,255,0.3)' }, editableProps: [{ key: 'text', label: 'Trigger Text', type: 'text' }, { key: 'tooltip', label: 'Tooltip Content', type: 'text' }, { key: 'position', label: 'Position', type: 'select', options: [{ label: 'Top', value: 'top' }, { label: 'Bottom', value: 'bottom' }, { label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }] },
  { name: 'Marquee', type: 'marquee', icon: '〰️', category: 'typography', description: 'Scrolling text marquee', defaultProps: { content: 'Scrolling announcement text here...', speed: 30, direction: 'left', pauseOnHover: true }, defaultStyles: { overflow: 'hidden', whiteSpace: 'nowrap', padding: '0.5rem 0', color: '#cbd5e1', fontSize: '0.875rem' }, editableProps: [{ key: 'content', label: 'Text', type: 'text' }, { key: 'speed', label: 'Speed (s)', type: 'number' }, { key: 'direction', label: 'Direction', type: 'select', options: [{ label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }] }, { key: 'pauseOnHover', label: 'Pause on Hover', type: 'toggle' }] },
];
