import type { BlockDefinition } from '../types';

export const WIDGETS_BLOCKS: BlockDefinition[] = [
// ═══════════════════════════════════════
// WIDGETS
// ═══════════════════════════════════════
  { name: 'Weather Widget', type: 'weather', icon: '🌤️', category: 'widgets', description: 'Weather forecast widget', defaultProps: { location: 'New York', unit: 'celsius', days: 5, apiKey: '' }, defaultStyles: { padding: '1.25rem', backgroundColor: 'rgba(59,130,246,0.08)', borderRadius: '0.75rem', border: '1px solid rgba(59,130,246,0.2)', maxWidth: '400px' }, editableProps: [{ key: 'location', label: 'Location', type: 'text' }, { key: 'unit', label: 'Unit', type: 'select', options: [{ label: 'Celsius', value: 'celsius' }, { label: 'Fahrenheit', value: 'fahrenheit' }] }, { key: 'days', label: 'Days', type: 'range' }] },
  { name: 'Clock', type: 'clock', icon: '🕐', category: 'widgets', description: 'Live analog or digital clock', defaultProps: { mode: 'digital', format: '12h', showSeconds: true, timezone: 'local' }, defaultStyles: { padding: '1rem', textAlign: 'center', fontFamily: 'monospace', fontSize: '2rem', color: '#7c3aed' }, editableProps: [{ key: 'mode', label: 'Mode', type: 'select', options: [{ label: 'Digital', value: 'digital' }, { label: 'Analog', value: 'analog' }] }, { key: 'format', label: 'Format', type: 'select', options: [{ label: '12h', value: '12h' }, { label: '24h', value: '24h' }] }, { key: 'showSeconds', label: 'Show Seconds', type: 'toggle' }] },
  { name: 'Calendar', type: 'calendar', icon: '📅', category: 'widgets', description: 'Event calendar widget', defaultProps: { title: 'Upcoming Events', events: [{ date: '2025-01-15', title: 'Event 1' }, { date: '2025-02-01', title: 'Event 2' }], layout: 'list' }, defaultStyles: { padding: '1.25rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)', maxWidth: '400px' }, editableProps: [{ key: 'title', label: 'Title', type: 'text' }, { key: 'layout', label: 'Layout', type: 'select', options: [{ label: 'List', value: 'list' }, { label: 'Grid', value: 'grid' }] }] },
  { name: 'QR Code', type: 'qr-code', icon: '📱', category: 'widgets', description: 'QR code generator', defaultProps: { text: 'https://example.com', size: 200, foreground: '#000000', background: '#ffffff' }, defaultStyles: { display: 'flex', justifyContent: 'center', padding: '1rem', marginBottom: '1rem' }, editableProps: [{ key: 'text', label: 'Content', type: 'text' }, { key: 'size', label: 'Size', type: 'number' }, { key: 'foreground', label: 'Foreground', type: 'color' }, { key: 'background', label: 'Background', type: 'color' }] },
  { name: 'PDF Viewer', type: 'pdf-viewer', icon: '📄', category: 'widgets', description: 'PDF document viewer', defaultProps: { url: 'https://example.com/document.pdf', height: '600px', toolbar: true }, defaultStyles: { width: '100%', height: '600px', border: 'none', borderRadius: '0.5rem', marginBottom: '1rem' }, editableProps: [{ key: 'url', label: 'PDF URL', type: 'text' }, { key: 'height', label: 'Height', type: 'text' }, { key: 'toolbar', label: 'Show Toolbar', type: 'toggle' }] },
  { name: 'Timer', type: 'timer', icon: '⏱️', category: 'widgets', description: 'Countdown or count-up timer', defaultProps: { mode: 'countdown', targetDate: '2025-12-31T23:59:59', label: 'Time Remaining', showDays: true, showHours: true, showMinutes: true, showSeconds: true }, defaultStyles: { display: 'flex', gap: '1rem', justifyContent: 'center', padding: '1.5rem', backgroundColor: 'rgba(124,58,237,0.08)', borderRadius: '0.75rem', border: '1px solid rgba(124,58,237,0.2)', fontFamily: 'monospace' }, editableProps: [{ key: 'mode', label: 'Mode', type: 'select', options: [{ label: 'Countdown', value: 'countdown' }, { label: 'Count Up', value: 'countup' }] }, { key: 'targetDate', label: 'Target Date', type: 'text' }, { key: 'label', label: 'Label', type: 'text' }, { key: 'showDays', label: 'Show Days', type: 'toggle' }, { key: 'showHours', label: 'Show Hours', type: 'toggle' }, { key: 'showMinutes', label: 'Show Minutes', type: 'toggle' }, { key: 'showSeconds', label: 'Show Seconds', type: 'toggle' }] },
  { name: 'RSS Feed', type: 'rss-feed', icon: '📡', category: 'widgets', description: 'RSS feed reader widget', defaultProps: { feedUrl: 'https://example.com/feed.xml', title: 'Latest News', count: 5, showDescription: true }, defaultStyles: { padding: '1.25rem', backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: '0.75rem', border: '1px solid rgba(255,255,255,0.1)' }, editableProps: [{ key: 'feedUrl', label: 'Feed URL', type: 'text' }, { key: 'title', label: 'Title', type: 'text' }, { key: 'count', label: 'Count', type: 'number' }, { key: 'showDescription', label: 'Show Description', type: 'toggle' }] },
  { name: 'Flip Clock', type: 'flip-clock', icon: '🕰️', category: 'widgets', description: 'Flip-style animated clock', defaultProps: { format: '24h', showDate: true, timezone: 'local' }, defaultStyles: { display: 'flex', gap: '0.25rem', justifyContent: 'center', padding: '1rem', fontFamily: '"Courier New", monospace', fontSize: '2rem', fontWeight: '700', color: '#ffffff' }, editableProps: [{ key: 'format', label: 'Format', type: 'select', options: [{ label: '24h', value: '24h' }, { label: '12h', value: '12h' }] }, { key: 'showDate', label: 'Show Date', type: 'toggle' }] },
];
