general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

model_list:
  - model_name: "confessions-model"
    litellm_params:
      model: "confessions-llm/my-model"

litellm_settings:
  custom_provider_map:
    - {"provider": "confessions-llm", "custom_handler": "agent.litellm_custom_handler.confessions_llm"}
