import { useState } from 'react';
import { Send, Loader2, Paperclip, BookOpen, Zap, Code2 } from 'lucide-react';
import { RickSanchez } from './RickSanchez';

interface SystemAgentProps {
  messages: any[];
  loading: boolean;
  onSendMessage: (message: string, file?: { data: string; mimeType: string; name: string }) => void;
  selectedRepo: string;
  trainingBoxOpen: boolean;
  setTrainingBoxOpen: (open: boolean) => void;
  onMemoryAdd: (content: string) => void;
}

export const SystemAgent = ({ 
  messages, 
  loading, 
  onSendMessage, 
  selectedRepo,
  trainingBoxOpen,
  setTrainingBoxOpen,
  onMemoryAdd
}: SystemAgentProps) => {
  const [input, setInput] = useState('');
  const [selectedFile, setSelectedFile] = useState<{ data: string; mimeType: string; name: string } | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 10 * 1024 * 1024) {
      alert('File too large. Max 10MB. *burp*');
      return;
    }

    const reader = new FileReader();
    reader.onload = (event) => {
      const base64 = event.target?.result as string;
      const data = base64.split(',')[1];
      setSelectedFile({
        data,
        mimeType: file.type,
        name: file.name
      });
    };
    reader.readAsDataURL(file);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if ((!input && !selectedFile) || !selectedRepo || loading) return;
    onSendMessage(input, selectedFile || undefined);
    setInput('');
    setSelectedFile(null);
  };

  return (
    <div className="bg-gradient-to-br from-blue-900/20 via-green-900/20 to-yellow-900/20 backdrop-blur-md border border-white/10 rounded-3xl p-6 flex flex-col h-full shadow-2xl">
      <div className="flex-1 overflow-y-auto space-y-4 pr-2 scrollbar-thin scrollbar-thumb-white/10">
        {messages.length === 0 && (
          <div className="h-full flex flex-col items-center justify-center text-white/20 space-y-6">
            <RickSanchez message="Select a repo and ask me something. I don't have all day. *burp*" />
            <p className="text-sm font-bold uppercase tracking-widest">System Agent Ready</p>
          </div>
        )}
        {messages.map((msg, i) => (
          <div 
            key={i} 
            className={`p-4 rounded-2xl max-w-[85%] ${
              msg.role === 'user' 
                ? 'bg-white/10 ml-auto border border-white/5' 
                : 'bg-green-900/20 border border-green-900/50 mr-auto'
            } transition-all hover:scale-[1.01]`}
          >
            {msg.file && (
              <div className="mb-2 p-2 bg-black/20 rounded-lg border border-white/5 flex items-center gap-2">
                <Paperclip className="w-3 h-3 text-green-400" />
                <span className="text-[10px] font-bold truncate">{msg.file.name}</span>
              </div>
            )}
            <p className="text-sm leading-relaxed">{msg.content}</p>
            {msg.type === 'code_change' && (
              <div className="mt-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-tighter text-green-400/60">
                <div className="w-1 h-1 rounded-full bg-green-400 animate-pulse" />
                Code Changes Proposed
              </div>
            )}
            {msg.imageUrl && (
              <div className="mt-3 rounded-xl overflow-hidden border border-white/10">
                <img src={msg.imageUrl} alt="Generated by AI" className="w-full h-auto" referrerPolicy="no-referrer" />
              </div>
            )}
          </div>
        ))}
        {loading && (
          <div className="bg-green-900/10 border border-green-900/30 p-4 rounded-2xl mr-auto animate-pulse flex items-center gap-3">
            <Loader2 className="w-4 h-4 animate-spin text-green-500" />
            <p className="text-xs font-medium text-green-500/70 italic">Rick is thinking... *burp*</p>
          </div>
        )}
      </div>

      {/* Training Box (Integrated) */}
      {trainingBoxOpen && (
        <div className="bg-black/40 p-4 rounded-xl mb-4 border border-green-500/20 backdrop-blur-xl animate-in slide-in-from-bottom-2">
          <div className="flex items-center gap-2 mb-2 text-[10px] font-bold uppercase tracking-widest text-green-500/60">
            <BookOpen className="w-3 h-3" />
            Memory Injection
          </div>
          <textarea
            placeholder="Teach me something new about your code..."
            className="w-full bg-transparent text-sm focus:outline-none text-white/80 placeholder:text-white/20 resize-none"
            rows={2}
            autoFocus
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                const val = (e.target as HTMLTextAreaElement).value;
                if (val) {
                  onMemoryAdd(val);
                  setTrainingBoxOpen(false);
                }
              }
            }}
          />
          <p className="text-[9px] text-white/20 mt-1">Press Enter to save memory</p>
        </div>
      )}

      {/* Selected File Preview */}
      {selectedFile && (
        <div className="bg-white/5 border border-white/10 p-3 rounded-xl mb-4 flex items-center justify-between animate-in fade-in slide-in-from-bottom-1">
          <div className="flex items-center gap-3 overflow-hidden">
            <div className="w-8 h-8 rounded-lg bg-green-500/20 flex items-center justify-center flex-shrink-0">
              <Paperclip className="w-4 h-4 text-green-400" />
            </div>
            <div className="min-w-0">
              <p className="text-xs font-bold text-white/80 truncate">{selectedFile.name}</p>
              <p className="text-[10px] text-white/40 uppercase tracking-widest">{selectedFile.mimeType}</p>
            </div>
          </div>
          <button 
            onClick={() => setSelectedFile(null)}
            className="text-white/20 hover:text-white/60 transition-colors p-1"
          >
            <Zap className="w-3 h-3 rotate-45" />
          </button>
        </div>
      )}

      <form onSubmit={handleSubmit} className="flex gap-2 items-center mt-4 pt-4 border-t border-white/10">
        <button 
          type="button" 
          onClick={() => setTrainingBoxOpen(!trainingBoxOpen)} 
          className={`p-3 rounded-xl border transition-all flex-shrink-0 hover:scale-105 active:scale-95 ${
            trainingBoxOpen 
              ? 'bg-green-600/20 border-green-600 text-green-400' 
              : 'bg-black/20 border-white/10 text-white/40 hover:text-white/60'
          }`}
          title="Train AI"
        >
          <BookOpen className="w-4 h-4" />
        </button>
        
        <label className={`p-3 backdrop-blur-md border rounded-xl cursor-pointer transition-all flex-shrink-0 hover:scale-105 active:scale-95 ${selectedFile ? 'bg-green-500/20 border-green-500 text-green-400' : 'bg-black/20 border-white/10 text-white/40 hover:text-white/60'}`}>
          <Paperclip className="w-4 h-4" />
          <input type="file" className="hidden" onChange={handleFileChange} />
        </label>

        <button
          type="button"
          onClick={() => onSendMessage("Rick, review this repository and propose some improvements. Don't be gentle. *burp*")}
          disabled={!selectedRepo || loading}
          className="p-3 rounded-xl border border-white/10 bg-black/20 text-white/40 hover:text-white/60 hover:bg-white/5 transition-all flex-shrink-0 hover:scale-105 active:scale-95"
          title="Review Repo"
        >
          <Code2 className="w-4 h-4" />
        </button>

        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={selectedRepo ? "Ask Rick anything..." : "Select a repo first..."}
          disabled={!selectedRepo || loading}
          className="flex-1 min-w-0 bg-black/20 backdrop-blur-md border border-white/10 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-green-600/50 transition-all disabled:opacity-50"
        />
        
        <button
          type="submit"
          disabled={loading || !selectedRepo || !input}
          className="bg-green-600 text-white px-5 py-3 rounded-xl font-bold text-sm hover:bg-green-500 disabled:opacity-50 transition-all flex-shrink-0 hover:scale-105 active:scale-95 shadow-lg shadow-green-900/20"
        >
          {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
        </button>
      </form>
    </div>
  );
};
