-- Superseded before production deployment.
-- The original 202609230500 draft included an incompatible replacement for
-- an unrelated legacy dashboard RPC and overlaps the audited weighted
-- metering schema. It was NOT applied to DreamMakerHub production.
-- Keep this timestamp as a no-op to avoid deploying the unsafe draft via
-- automatic migration runners. The audited, production-applied replacement:
-- 20260927120517_coder_customer_metering_core_20260927.sql
-- Actual production Supabase migration version: 20260927120517.
-- Customer provisioning remains gated until independent identity, template,
-- hard-stop and private-gateway verification.
