-- Unified DreamMakerHub usage ledger across dreammakerhub.website, AI-PLAYGROUND and NPC-AI-SIM.
-- Service-role only reservation keeps entitlements and purchased balances authoritative.

ALTER TABLE public.user_token_balances
  ADD COLUMN IF NOT EXISTS purchased_render_credits BIGINT NOT NULL DEFAULT 0
  CHECK (purchased_render_credits >= 0);

ALTER TABLE public.billable_usage_counters
  DROP CONSTRAINT IF EXISTS billable_usage_counters_feature_check;
ALTER TABLE public.billable_usage_counters
  ADD CONSTRAINT billable_usage_counters_feature_check
  CHECK (feature IN ('ai_tokens','ai_requests','agent_requests','workspace_launches','render_credits'));

CREATE TABLE IF NOT EXISTS public.cross_repo_usage_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period_start DATE NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('dreammakerhub','ai-playground','npc-ai-sim')),
  feature TEXT NOT NULL CHECK (feature IN ('ai_tokens','ai_requests','agent_requests','workspace_launches','render_credits')),
  units BIGINT NOT NULL CHECK (units > 0),
  purchased_units BIGINT NOT NULL DEFAULT 0 CHECK (purchased_units >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS cross_repo_usage_events_user_period_idx
  ON public.cross_repo_usage_events(user_id, period_start, created_at DESC);
CREATE INDEX IF NOT EXISTS cross_repo_usage_events_source_idx
  ON public.cross_repo_usage_events(source, created_at DESC);

ALTER TABLE public.cross_repo_usage_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.cross_repo_usage_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON TABLE public.cross_repo_usage_events TO service_role;

CREATE OR REPLACE FUNCTION public.reserve_billable_units_v2(
  p_user_id UUID,
  p_feature TEXT,
  p_units INTEGER,
  p_limit INTEGER,
  p_source TEXT
) RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  month_start DATE := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
  current_units BIGINT := 0;
  v_purchased_tokens BIGINT := 0;
  v_purchased_render BIGINT := 0;
  included_remaining BIGINT := 0;
  purchased_needed BIGINT := 0;
BEGIN
  IF p_user_id IS NULL
     OR p_feature NOT IN ('ai_tokens','ai_requests','agent_requests','workspace_launches','render_credits')
     OR p_source NOT IN ('dreammakerhub','ai-playground','npc-ai-sim')
     OR p_units IS NULL OR p_units < 1 OR p_units > 1000000
     OR p_limit IS NULL OR p_limit < 0 THEN
    RETURN false;
  END IF;

  INSERT INTO public.billable_usage_counters(user_id, period_start, feature, units)
  VALUES (p_user_id, month_start, p_feature, 0)
  ON CONFLICT (user_id, period_start, feature) DO NOTHING;

  SELECT units INTO current_units
  FROM public.billable_usage_counters
  WHERE user_id = p_user_id AND period_start = month_start AND feature = p_feature
  FOR UPDATE;

  IF p_feature IN ('ai_tokens','render_credits') THEN
    INSERT INTO public.user_token_balances(user_id, purchased_tokens, purchased_render_credits, updated_at)
    VALUES (p_user_id, 0, 0, now())
    ON CONFLICT (user_id) DO NOTHING;

    SELECT purchased_tokens, purchased_render_credits
      INTO v_purchased_tokens, v_purchased_render
    FROM public.user_token_balances
    WHERE user_id = p_user_id
    FOR UPDATE;

    included_remaining := GREATEST(p_limit::BIGINT - current_units, 0);
    purchased_needed := GREATEST(p_units::BIGINT - included_remaining, 0);

    IF p_feature = 'ai_tokens' AND purchased_needed > v_purchased_tokens THEN
      RETURN false;
    END IF;
    IF p_feature = 'render_credits' AND purchased_needed > v_purchased_render THEN
      RETURN false;
    END IF;

    UPDATE public.billable_usage_counters
       SET units = units + p_units, updated_at = now()
     WHERE user_id = p_user_id AND period_start = month_start AND feature = p_feature;

    IF purchased_needed > 0 AND p_feature = 'ai_tokens' THEN
      UPDATE public.user_token_balances
         SET purchased_tokens = purchased_tokens - purchased_needed, updated_at = now()
       WHERE user_id = p_user_id;
    ELSIF purchased_needed > 0 AND p_feature = 'render_credits' THEN
      UPDATE public.user_token_balances
         SET purchased_render_credits = purchased_render_credits - purchased_needed, updated_at = now()
       WHERE user_id = p_user_id;
    END IF;
  ELSE
    IF current_units > p_limit::BIGINT - p_units::BIGINT THEN
      RETURN false;
    END IF;

    UPDATE public.billable_usage_counters
       SET units = units + p_units, updated_at = now()
     WHERE user_id = p_user_id AND period_start = month_start AND feature = p_feature;
  END IF;

  INSERT INTO public.cross_repo_usage_events(user_id, period_start, source, feature, units, purchased_units)
  VALUES (p_user_id, month_start, p_source, p_feature, p_units, purchased_needed);

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_billable_units_v2(UUID,TEXT,INTEGER,INTEGER,TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_billable_units_v2(UUID,TEXT,INTEGER,INTEGER,TEXT)
  TO service_role;

CREATE TABLE IF NOT EXISTS public.render_credit_purchase_events (
  stripe_checkout_session_id TEXT PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pack_id TEXT NOT NULL,
  credits BIGINT NOT NULL CHECK (credits > 0),
  stripe_price_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS render_credit_purchase_events_user_created_idx
  ON public.render_credit_purchase_events(user_id, created_at DESC);

ALTER TABLE public.render_credit_purchase_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read their own render credit purchases" ON public.render_credit_purchase_events;
CREATE POLICY "Users can read their own render credit purchases"
  ON public.render_credit_purchase_events FOR SELECT TO authenticated
  USING (auth.uid() = user_id);
GRANT SELECT ON public.render_credit_purchase_events TO authenticated;
GRANT ALL ON public.render_credit_purchase_events TO service_role;

CREATE OR REPLACE FUNCTION public.grant_purchased_render_credits(
  p_user_id UUID,
  p_checkout_session_id TEXT,
  p_pack_id TEXT,
  p_credits BIGINT,
  p_price_id TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inserted INTEGER;
BEGIN
  IF p_user_id IS NULL OR p_checkout_session_id IS NULL OR length(p_checkout_session_id) < 5
     OR p_pack_id IS NULL OR p_credits <= 0 OR p_price_id IS NULL THEN
    RAISE EXCEPTION 'Invalid render credit grant';
  END IF;

  INSERT INTO public.render_credit_purchase_events(
    stripe_checkout_session_id, user_id, pack_id, credits, stripe_price_id
  )
  VALUES (p_checkout_session_id, p_user_id, p_pack_id, p_credits, p_price_id)
  ON CONFLICT (stripe_checkout_session_id) DO NOTHING;

  GET DIAGNOSTICS inserted = ROW_COUNT;
  IF inserted = 0 THEN RETURN false; END IF;

  INSERT INTO public.user_token_balances(user_id, purchased_tokens, purchased_render_credits, updated_at)
  VALUES (p_user_id, 0, p_credits, now())
  ON CONFLICT (user_id)
  DO UPDATE SET
    purchased_render_credits = public.user_token_balances.purchased_render_credits + EXCLUDED.purchased_render_credits,
    updated_at = now();

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.grant_purchased_render_credits(UUID,TEXT,TEXT,BIGINT,TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.grant_purchased_render_credits(UUID,TEXT,TEXT,BIGINT,TEXT)
  TO service_role;

CREATE OR REPLACE FUNCTION public.get_cross_repo_usage_summary(p_user_id UUID)
RETURNS JSON
LANGUAGE SQL
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT json_build_object(
    'period_start', date_trunc('month', now() AT TIME ZONE 'UTC')::date,
    'ai_tokens_used', COALESCE(SUM(units) FILTER (WHERE feature='ai_tokens'),0),
    'api_requests_used', COALESCE(SUM(units) FILTER (WHERE feature='ai_requests'),0),
    'render_credits_used', COALESCE(SUM(units) FILTER (WHERE feature='render_credits'),0),
    'by_source', COALESCE((
      SELECT json_object_agg(source, payload)
      FROM (
        SELECT source, json_build_object(
          'ai_tokens', COALESCE(SUM(units) FILTER (WHERE feature='ai_tokens'),0),
          'api_requests', COALESCE(SUM(units) FILTER (WHERE feature='ai_requests'),0),
          'render_credits', COALESCE(SUM(units) FILTER (WHERE feature='render_credits'),0)
        ) payload
        FROM public.cross_repo_usage_events e2
        WHERE e2.user_id=p_user_id
          AND e2.period_start=date_trunc('month', now() AT TIME ZONE 'UTC')::date
        GROUP BY source
      ) source_totals
    ), '{}'::json)
  )
  FROM public.cross_repo_usage_events e
  WHERE e.user_id=p_user_id
    AND e.period_start=date_trunc('month', now() AT TIME ZONE 'UTC')::date;
$$;

REVOKE ALL ON FUNCTION public.get_cross_repo_usage_summary(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_cross_repo_usage_summary(UUID) TO service_role;


CREATE OR REPLACE FUNCTION public.get_usage_totals_for_alerts(p_user_id UUID)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
  v_period_start DATE := date_trunc('month', now() AT TIME ZONE 'UTC')::date;
  plan_name TEXT := 'free';
  result JSON;
BEGIN
  SELECT COALESCE(s.plan, 'free') INTO plan_name
  FROM public.subscriptions s
  WHERE s.user_id = p_user_id AND s.status IN ('active','trialing')
  ORDER BY s.updated_at DESC
  LIMIT 1;

  SELECT json_build_object(
    'plan', COALESCE(plan_name, 'free'),
    'period_start', v_period_start,
    'api_requests', COALESCE((
      SELECT units FROM public.billable_usage_counters
      WHERE user_id=p_user_id AND period_start=v_period_start AND feature='ai_requests'
    ),0),
    'ai_tokens', COALESCE((
      SELECT units FROM public.billable_usage_counters
      WHERE user_id=p_user_id AND period_start=v_period_start AND feature='ai_tokens'
    ),0),
    'three_d_generations', COALESCE((
      SELECT units FROM public.billable_usage_counters
      WHERE user_id=p_user_id AND period_start=v_period_start AND feature='render_credits'
    ),0),
    'storage', COALESCE((
      SELECT SUM(storage_used) FROM public.projects
      WHERE owner_id=p_user_id AND status <> 'deleted'
    ),0)
  ) INTO result;

  RETURN result;
END $$;

REVOKE ALL ON FUNCTION public.get_usage_totals_for_alerts(UUID) FROM PUBLIC, authenticated;
GRANT EXECUTE ON FUNCTION public.get_usage_totals_for_alerts(UUID) TO service_role;
